import {test,expect} from 'bun:test';
import {Actions,type Snapshot} from '../src/chatgpt/actions.ts';
const snap=(controls:any[]=[],messages:any[]=[]):Snapshot=>({epoch:'e',url:'https://chatgpt.com/c/test',title:'test',text:'',controls,messages,media:[]});
const make=(snapshot:()=>Snapshot,write:(op:string,args:any)=>void=()=>{})=>new Actions({call:async(op:string,args:any)=>{if(op==='snapshot')return snapshot();write(op,args);return {};}} as any);
test('model selection uses observed label and verifies selected state after clicking',async()=>{
 let selected=false;const writes:any[]=[];
 const a=make(()=>snap([{name:'Select model',role:'menuitem'},{name:'GPT-5.5\nLeaving on October 14',role:'menuitemradio',ref:7,checked:selected}]),(op,args)=>{writes.push({op,args});if(op==='action'&&args.kind==='click'&&args.ref===7)selected=true;});
 expect(await a.choose('model','GPT-5.5')).toMatchObject({selected:'GPT-5.5',verified:true});
 expect(writes.filter(x=>x.op==='action'&&x.args.kind==='click')).toEqual([{op:'action',args:{ref:7,epoch:'e',kind:'click'}}]);
 await expect(a.choose('model','invented-model')).rejects.toThrow('Observed options');
 expect(writes.filter(x=>x.op==='action'&&x.args.kind==='click')).toHaveLength(1);
});
test('active response blocks picker changes',async()=>{const a=make(()=>snap([{testId:'stop-button'}]));await expect(a.choose('model','Latest')).rejects.toThrow('Stop it before changing');});
test('power selection discovers labels and restores original on invalid label',async()=>{
 let index=3;const labels=['Light','Medium','High','Extended','Pro'];
 const a=make(()=>snap([{name:'Select model',role:'menuitem'},{name:'Latest',role:'menuitemradio',checked:true},{name:'Power',role:'menuitem',ref:4,context:labels[index-1]+', '+index+' of 5.'}]),(op,args)=>{if(op==='key'&&args.key==='ArrowLeft')index--;if(op==='key'&&args.key==='ArrowRight')index++;});
 expect((await a.choose('effort','light')).selected).toBe('Light');expect(index).toBe(1);index=3;
 await expect(a.choose('effort','imaginary')).rejects.toThrow('Restored previous power');expect(index).toBe(3);
 expect((await a.options()).efforts).toEqual(labels);expect(index).toBe(3);
},40000);
test('model click without selected-state readback never returns a verified receipt',async()=>{
 const a=make(()=>snap([{name:'Select model',role:'menuitem'},{name:'Latest',role:'menuitemradio',ref:1,checked:true},{name:'GPT-5.5',role:'menuitemradio',ref:2,checked:false}]));
 await expect(a.choose('model','GPT-5.5')).rejects.toThrow('did not confirm');
});
test('per-message control association rejects ambiguous actions',async()=>{const a=make(()=>snap([{name:'Edit message',ref:1},{name:'Edit message',ref:2}],[{id:'u1',role:'user'},{id:'u2',role:'user'}]));await expect(a.turn('u1','user',['Edit message'])).rejects.toThrow('uniquely associate');});
test('per-message control metadata selects exact requested turn',async()=>{const a=make(()=>snap([{name:'Edit message',ref:1,messageId:'u1'},{name:'Edit message',ref:2,messageId:'u2'}],[{id:'u1',role:'user'},{id:'u2',role:'user'}]));expect((await a.turn('u1','user',['Edit message'])).c.ref).toBe(1);await expect(a.turn('missing','user',['Edit message'])).rejects.toThrow('not visible');});
test('branch follows exact website submenu and returns new identity',async()=>{let phase=0;const a=make(()=>{const s=snap(phase===0?[{name:'More actions',messageId:'a1',ref:1}]:phase===1?[{name:'Open new branch',role:'menuitem',ref:2}]:[{name:'Branch in new Chat',role:'menuitem',ref:3}],[{id:'a1',role:'assistant'}]);if(phase===3)s.url='https://chatgpt.com/c/branch';return s;},op=>{if(op==='action')phase++;});expect((await a.branch('a1')).conversation).toBe('branch');expect(phase).toBe(3);});
test('response replacement on the same message id is streamed',async()=>{const before=snap([],[{id:'a',role:'assistant',text:'old'}]);const a=make(()=>snap([],[{id:'a',role:'assistant',text:'new'}]));const events:any[]=[];const result=await a.waitReply(before,e=>events.push(e),5000);expect(result.text).toBe('new');expect(events.some(e=>e.type==='text'&&e.text==='new')).toBe(true);});
test('completion waits for continuous inactivity so post-stop DOM animation is not truncated',async()=>{let reads=0;const before=snap();const a=make(()=>{reads++;if(reads<=9)return snap([{testId:'stop-button'}],[{id:'answer',role:'assistant',text:'Proto'}]);if(reads===10)return snap([],[{id:'answer',role:'assistant',text:'Proto'}]);return snap([],[{id:'answer',role:'assistant',text:'Protocol complete'}]);});const events:any[]=[];const result=await a.waitReply(before,e=>events.push(e),7000);expect(result.text).toBe('Protocol complete');expect(events.filter(e=>e.type==='text').map(e=>e.text).join('')).toBe('Protocol complete');});
test('empty DOM placeholder uses only a finished receipt on current branch',async()=>{const a=new Actions({call:async(op:string)=>op==='snapshot'?snap([],[{id:'new',role:'assistant',text:''}]):{status:200,body:{current_node:'n',mapping:{n:{parent:null,message:{id:'new',author:{role:'assistant'},status:'finished_successfully',content:{parts:['receipt answer']}}}}}}} as any);const result=await a.waitReply(snap(),()=>{},4500);expect(result.text).toBe('receipt answer');expect(result.source).toBe('website conversation receipt');});
test('observed submission can recover a finished reply absent from the DOM by its exact branch anchor',async()=>{const current=snap([],[{id:'submitted-user',role:'user',text:'new prompt'}]);const a=new Actions({call:async(op:string)=>op==='snapshot'?current:{status:200,body:{current_node:'answer',mapping:{old:{parent:null,message:{id:'old-answer',author:{role:'assistant'},status:'finished_successfully',content:{parts:['unrelated old answer']}}},user:{parent:'old',message:{id:'submitted-user',author:{role:'user'},status:'finished_successfully',content:{parts:['new prompt']}}},answer:{parent:'user',message:{id:'receipt-answer',author:{role:'assistant'},status:'finished_successfully',content:{parts:['anchored receipt answer']}}}}}}} as any);const result=await a.waitReply(snap(),()=>{},4500);expect(result.text).toBe('anchored receipt answer');expect(result.messages.map((m:any)=>m.id)).toEqual(['receipt-answer']);expect(result.source).toBe('website conversation receipt');});
test('receipt recovery refuses a current branch without the exact observed submission id',async()=>{const current=snap([],[{id:'submitted-user',role:'user',text:'new prompt'}]);let reads=0;const a=new Actions({call:async(op:string)=>{if(op==='snapshot')return current;reads++;return {status:200,body:{current_node:'answer',mapping:{user:{parent:null,message:{id:'different-user',author:{role:'user'},status:'finished_successfully',content:{parts:['other prompt']}}},answer:{parent:'user',message:{id:'receipt-answer',author:{role:'assistant'},status:'finished_successfully',content:{parts:['wrong answer']}}}}}};}} as any);await expect(a.waitReply(snap(),()=>{},3200)).rejects.toThrow('Timed out');expect(reads).toBeGreaterThan(0);});
test('empty placeholders and finished receipts on another branch never report success',async()=>{const a=new Actions({call:async(op:string)=>op==='snapshot'?snap([],[{id:'other',role:'assistant',text:''}]):{status:200,body:{current_node:'n',mapping:{n:{parent:null,message:{id:'current',author:{role:'assistant'},status:'in_progress',content:{parts:['']}}},other:{parent:null,message:{id:'other',author:{role:'assistant'},status:'finished_successfully',content:{parts:['wrong branch']}}}}}}} as any);await expect(a.waitReply(snap(),()=>{},3000)).rejects.toThrow('Timed out');});
test('receipt rate limit enters a cooldown instead of polling again',async()=>{let reads=0;const a=make(()=>snap([],[{id:'new',role:'assistant',text:''}]));a.readReceipt=async()=>{reads++;throw new Error('HTTP 429');};await expect(a.waitReply(snap(),()=>{},5000)).rejects.toThrow('Timed out');expect(reads).toBe(1);},7000);

test('quoted error prose does not fail an otherwise completed website reply',async()=>{const current={...snap([],[{id:'answer',role:'assistant',text:'The log says Something went wrong; here is the explanation.'}]),text:'Something went wrong',notices:[]};const a=make(()=>current);expect((await a.waitReply(snap(),()=>{},4000)).text).toContain('here is the explanation');});
test('visible site failure notice stops observation without replaying a write',async()=>{let writes=0;const a=make(()=>({...snap(),notices:[{role:'alert',text:'Something went wrong'}]}),()=>writes++);await expect(a.waitReply(snap(),()=>{},3000)).rejects.toThrow('ChatGPT reported a problem');expect(writes).toBe(0);});
