import {test,expect} from 'bun:test';
import {capabilityReport} from '../src/chatgpt/capabilities.ts';
import {adapter} from '../src/chatgpt/adapters.ts';
test('partial and historical evidence never becomes current successful parity',()=>{const evidence={'media.list':{operation:'media.list',adapter:adapter().version,observedSuccess:true,complete:false},'chat.send':{operation:'chat.send',adapter:'old-version',observedSuccess:true},'chat.edit':{arbitrary:true}};const r=capabilityReport({},[],evidence);expect(r.capabilities.find(x=>x.id==='media.library')?.status).toBe('observed-partial');expect(r.capabilities.find(x=>x.id==='conversations.send')?.status).toBe('historical-operation');expect(r.capabilities.find(x=>x.id==='conversations.edit')?.status).toBe('implemented-unverified');expect(r.complete).toBe(false);expect(r.capabilities.every(c=>c.parityVerified===false)).toBe(true);});
test('nested discovery preserves trigger paths, duplicates and unvisited settings',()=>{const c={name:'Same',role:'button'};const r=capabilityReport({navigationComplete:true,complete:true,sections:[{name:'General',controls:[c],nested:[{trigger:'Appearance',controls:[c],confirmed:false,evidence:'opened-without-selection',nested:[{trigger:'Advanced',controls:[c]}]}],unexplored:['Language']}]},[]);expect(r.discoveredControls.length).toBe(3);expect(new Set(r.discoveredControls.map(c=>c.id)).size).toBe(3);expect(r.discoveredControls[2].path).toEqual(['Appearance','Advanced']);expect(r.settingsCoverage.navigationComplete).toBe(true);expect(r.settingsCoverage.complete).toBe(false);expect(r.settingsCoverage.unexplored).toEqual([{section:'General',control:'Language'}]);expect(r.discoveredControls.every(c=>!c.mutationVerified&&c.requiresFreshReference)).toBe(true);});
test('bootstrap GPT and local takeout evidence do not imply owned GPT or official export coverage',()=>{const proof=(operation:string)=>({operation,adapter:adapter().version,observedSuccess:true,complete:true});const r=capabilityReport({},[{scope:'gpts:bootstrap',complete:true,count:0}],{'gpts.bootstrap':proof('gpts.bootstrap'),'takeout.run':proof('takeout.run')});expect(r.capabilities.find(x=>x.id==='gpts.bootstrap')).toMatchObject({scope:'bootstrap-gizmos',status:'operation-completed'});expect(r.capabilities.find(x=>x.id==='gpts.list')?.status).toBe('implemented-unverified');expect(r.capabilities.find(x=>x.id==='gpts.owned-list')?.status).toBe('implemented-unverified');expect(r.capabilities.find(x=>x.id==='account.takeout-original')?.status).toBe('implemented-unverified');for(const surface of ['health','sites','work','apps','library','images'])expect(r.capabilities.some(x=>x.surface===surface)).toBe(true);});

test('a successful dispatch remains a semantic gap and is counted separately',()=>{const r=capabilityReport({},[],{'voice.start':{operation:'voice.start',adapter:adapter().version,observedSuccess:true}});expect(r.capabilities.find(c=>c.id==='media.voice')?.status).toBe('operation-completed');expect(r.gaps).toContainEqual({id:'media.voice',status:'semantic-unverified'});expect(r.summary.currentOperationCompletions).toBeGreaterThan(0);expect(r.summary.semanticParityVerified).toBe(0);expect(r.summary.semanticVerificationGaps).toBe(r.capabilities.length);});
test('queue scope and model/media controls are explicit without native parity',()=>{const r=capabilityReport({});for(const [id,operation] of [['models.effort','chat.effort'],['models.select','chat.model'],['queue.run','queue.run'],['media.audio-output-capture','audio.output.capture'],['account.invoice-watch','invoices.watch'],['conversations.reconcile','chat.reconcile']])expect(r.capabilities.find(c=>c.id===id)?.operation).toBe(operation);expect(r.capabilities.find(c=>c.id==='queue.run')).toMatchObject({scope:'local-durable-cli',parityVerified:false});expect(r.capabilities.find(c=>c.id==='queue.native-steer')).toMatchObject({scope:'website-native',status:'unmapped'});});
test('observed surface and duplicate setting controls remain distinct discovery evidence',()=>{const control={name:'Menu',role:'button'},r=capabilityReport({sections:[{name:'General',controls:[control,control]}]},[],{},{surfaces:{'/library':{at:'2026-09-15T00:00:00Z',controls:[control,control]},'/broken':{controls:null}}});expect(new Set(r.discoveredControls.map(c=>c.id)).size).toBe(2);expect(new Set(r.discoveredSurfaceControls.map(c=>c.id)).size).toBe(2);expect(r.discoveredSurfaceControls.every(c=>c.mutationVerified===false&&c.requiresFreshReference)).toBe(true);expect(r.summary.discoveredSurfaceControls).toBe(2);});
