import {test,expect} from 'bun:test';
import {verifyHarnessRun} from '../src/chatgpt/harness-verify.ts';
const token='bridge-fixture';
function fixture(){
 const selection={mode:{verified:true,selected:'Chat'},model:{verified:true,selected:'Latest'},effort:{verified:true,selected:'Instant'}};
 const row=(id:string,name:string,text:string,n:number)=>({agentId:id,name,text,kind:'turn',requestId:id+'-'+n,submitted:true,started:new Date(1000*n).toISOString(),submittedAt:new Date(1000*n+50).toISOString(),finished:new Date(1000*n+2000).toISOString(),conversation:'chat-'+id,url:'https://chatgpt.com/c/chat-'+id,driver:{identity:{verified:true,userId:'user',account:'fixture'},selection:structuredClone(selection),submission:{verified:true}}});
 const driverTurns=[...Array.from({length:6},(_,i)=>row('parent','parent',i===5?'ALPHA_FINAL:42 BETA_FINAL:17 TOKEN:'+token:'Parent result',i)),...['alpha','beta'].flatMap(name=>(name==='alpha'?[42,47,42]:[17,42,17]).map((value,i)=>row(name,name,name.toUpperCase()+'_VALUE:'+value+' TOKEN:'+token,i+1)))];
 const messages=[['alpha',42,10],['beta',17,11],['alpha',47,20],['beta',42,21],['alpha',42,30],['beta',17,31]].map(([name,value,seq])=>({seq,type:'agent.message',agentId:'parent',fromAgentId:name,fromName:name,text:String(name).toUpperCase()+'_VALUE:'+value+' TOKEN:'+token}));
 const delivered=[[],[10,11],[20],[21],[30],[31]];
 return {test:true,account:{id:'fixture',userId:'user'},model:'Latest',effort:'Instant',requestedParentTurns:6,parentTurns:Array.from({length:6},(_,i)=>({number:i+1,deliveredEvents:delivered[i].length,deliveredEventSeqs:delivered[i],text:driverTurns[i].text})),driverTurns,idle:true,snapshot:{counts:{pending:0},calls:[{status:'complete'}]},events:[{seq:1,type:'turn.started',agentId:'parent',turnId:'turn-1'},{seq:2,type:'turn.event',agentId:'parent',turnId:'turn-1',event:{type:'protocol.replace'}},{seq:3,type:'tool.call',agentId:'parent',turnId:'turn-1',source:'stream'},{seq:4,type:'turn.completed',agentId:'parent',turnId:'turn-1'},...messages]};
}
test('verifier accepts nested receipts, streamed task dispatch, delivered child events and a grounded final',()=>{const state=fixture(),verified=verifyHarnessRun(state,token);expect(verified.complete).toBe(true);expect(verified.alpha.observed).toEqual([42,47,42]);expect(verified.deliveredAlpha.observed).toEqual([42,47,42]);expect(verified.deliveryParentTurns).toEqual([2,3,4,5,6]);expect(verified.finalGrounded).toBe(true);});
test('verified flags alone do not prove the requested model, effort or account',()=>{for(const alter of [(row:any)=>delete row.driver.selection,(row:any)=>row.driver.selection.mode.selected='Work',(row:any)=>row.driver.selection.model.selected='Other',(row:any)=>row.driver.selection.effort.verified=false,(row:any)=>row.driver.identity.userId='other']){const state=fixture();alter(state.driverTurns[0]);expect(verifyHarnessRun(state,token).complete).toBe(false);}});
test('unordered values or missing final resets cannot satisfy arithmetic verification',()=>{for(const values of [[47,42,42],[42,47],[42,47,999]]){const state=fixture();state.driverTurns=state.driverTurns.filter(row=>row.name!=='alpha'||values.length===3);if(values.length===3){state.driverTurns.filter(row=>row.name==='alpha').forEach((row,i)=>row.text='ALPHA_VALUE:'+values[i]+' TOKEN:'+token);}expect(verifyHarnessRun(state,token).complete).toBe(false);}});
test('bootstrap answers and token-prefix matches do not establish successful child task replies',()=>{const state=fixture();state.driverTurns.find(row=>row.name==='alpha')!.kind='bootstrap';expect(verifyHarnessRun(state,token).alpha.verified).toBe(false);const other=fixture();other.driverTurns.find(row=>row.name==='alpha')!.text+='-wrong';expect(verifyHarnessRun(other,token).alpha.verified).toBe(false);});
test('bootstrap overlap, ungrounded finals and undelivered expected values cannot satisfy async acceptance',()=>{for(const change of [(state:any)=>state.driverTurns.filter((row:any)=>row.agentId!=='parent').forEach((row:any)=>row.kind='bootstrap'),(state:any)=>state.parentTurns.at(-1).text='ALPHA_FINAL:47 BETA_FINAL:17 TOKEN:'+token,(state:any)=>state.parentTurns[4].deliveredEventSeqs=[],(state:any)=>state.parentTurns[4].deliveredEvents=0]){const state=fixture();change(state);expect(verifyHarnessRun(state,token).complete).toBe(false);}});
test('delivery evidence must reference unique persisted events from two children across later turns',()=>{for(const change of [(state:any)=>state.parentTurns[2].deliveredEventSeqs=[999],(state:any)=>state.parentTurns[2].deliveredEventSeqs=[10],(state:any)=>{state.parentTurns[1].deliveredEventSeqs=[10,11,20,21,30,31];state.parentTurns[1].deliveredEvents=6;for(let i=2;i<6;i++){state.parentTurns[i].deliveredEventSeqs=[];state.parentTurns[i].deliveredEvents=0;}},(state:any)=>state.events.find((event:any)=>event.seq===31).fromName='alpha']){const state=fixture();change(state);expect(verifyHarnessRun(state,token).complete).toBe(false);}});
test('final-only dispatch, missing stream chunks and failed broker calls remain partial',()=>{for(const change of [(state:any)=>state.events[1].event.type='text',(state:any)=>state.events[2].turnId='other-turn',(state:any)=>state.events[2].source='final',(state:any)=>state.events.splice(1,1),(state:any)=>state.events.push({seq:5,type:'tool.error',agentId:'parent',error:{code:'AGENT_EXISTS'}}),(state:any)=>state.events.push({seq:5,type:'protocol.error',agentId:'parent'}),(state:any)=>state.snapshot.calls[0].status='error']){const state=fixture();change(state);expect(verifyHarnessRun(state,token).complete).toBe(false);}});
test('child context drift, shared conversations, uncertain writes and pending work fail closed',()=>{for(const change of [(state:any)=>{const row=state.driverTurns.find((row:any)=>row.name==='alpha');row.conversation='other';row.url='https://chatgpt.com/c/other';},(state:any)=>state.driverTurns.filter((row:any)=>row.name==='beta').forEach((row:any)=>{row.conversation='chat-alpha';row.url='https://chatgpt.com/c/chat-alpha';}),(state:any)=>state.driverTurns[0].submitted=false,(state:any)=>state.driverTurns[0].error={code:'OUTCOME_UNKNOWN'},(state:any)=>state.snapshot.counts.pending=1]){const state=fixture();change(state);expect(verifyHarnessRun(state,token).complete).toBe(false);}});
test('verification is read-only and requires all requested parent turns',()=>{const state=fixture(),original=JSON.stringify(state);verifyHarnessRun(state,token);expect(JSON.stringify(state)).toBe(original);state.parentTurns.pop();expect(verifyHarnessRun(state,token).complete).toBe(false);});
