import {test,expect} from 'bun:test';
import {StreamToolParser,harnessBootstrap,MAX_TOOL_CALLS,type ToolCall,type ToolProtocolError} from '../src/chatgpt/harness-protocol.ts';
const frame=(run:string,call:ToolCall)=>`<tool_call run="${run}">\n${JSON.stringify(call)}\n</tool_call>`;
function fixture(maxFrameBytes?:number){const calls:ToolCall[]=[],errors:ToolProtocolError[]=[];return {calls,errors,parser:new StreamToolParser({runId:'run-1',agentId:'agent-1',onCall:call=>calls.push(call),onError:error=>errors.push(error),maxFrameBytes})};}

test('dispatches one complete frame across every chunk boundary',()=>{const value=frame('run-1',{id:'c1',tool:'echo',args:{text:'שלום 🌍'}});for(let split=1;split<value.length;split++){const f=fixture();f.parser.append(value.slice(0,split));expect(f.calls).toHaveLength(0);f.parser.append(value.slice(split));f.parser.finish();expect(f.calls).toEqual([{id:'c1',tool:'echo',args:{text:'שלום 🌍'}}]);expect(f.errors).toHaveLength(0);}});
test('dispatches several independent frames from one streaming reply',()=>{const f=fixture();const first=frame('run-1',{id:'parallel-1',tool:'agents.list',args:{}}),second=frame('run-1',{id:'parallel-2',tool:'echo',args:{value:'ready'}});f.parser.append(first+'\n'+second.slice(0,23));expect(f.calls.map(call=>call.id)).toEqual(['parallel-1']);f.parser.append(second.slice(23));f.parser.finish();expect(f.calls.map(call=>call.id)).toEqual(['parallel-1','parallel-2']);expect(f.errors).toHaveLength(0);});
test('ignores fenced examples and accepts an unfenced frame',()=>{const f=fixture(),example=frame('run-1',{id:'example',tool:'echo',args:{text:'never'}}),real=frame('run-1',{id:'real',tool:'agents.list',args:{}});f.parser.append('```json\n'+example+'\n```\n'+real);f.parser.finish();expect(f.calls.map(x=>x.id)).toEqual(['real']);expect(f.errors).toHaveLength(0);});
test('quoted closing text, braces, escapes and Unicode stay inside JSON strings',()=>{const f=fixture();f.parser.append(frame('run-1',{id:'quoted',tool:'echo',args:{text:'literal </tool_call> { } " quote \u2028 café'}}));f.parser.finish();expect(f.calls).toEqual([{id:'quoted',tool:'echo',args:{text:'literal </tool_call> { } " quote \u2028 café'}}]);expect(f.errors).toHaveLength(0);});
test('replace and replay deduplicate canonical payload while changed payload conflicts',()=>{const f=fixture(),first=frame('run-1',{id:'same',tool:'echo',args:{b:2,a:1}});f.parser.append(first.slice(0,20));f.parser.replace(first);f.parser.replace(first+'\n'+frame('run-1',{id:'same',tool:'echo',args:{a:1,b:2}}));expect(f.calls).toHaveLength(1);f.parser.replace(frame('run-1',{id:'same',tool:'echo',args:{a:2,b:2}}));f.parser.finish();expect(f.calls).toHaveLength(1);expect(f.errors.map(x=>x.code)).toContain('CALL_ID_CONFLICT');});
test('mismatched run nonce never dispatches',()=>{const f=fixture();f.parser.append(frame('other-run',{id:'c1',tool:'echo',args:{}}));f.parser.finish();expect(f.calls).toHaveLength(0);expect(f.errors.map(x=>x.code)).toContain('RUN_MISMATCH');});
test('malformed, incomplete and capped frames never dispatch',()=>{const malformed=fixture();malformed.parser.append('<tool_call run="run-1">\n{"id":"x","tool":"echo","args":{}\n</tool_call>');malformed.parser.finish();expect(malformed.calls).toHaveLength(0);expect(malformed.errors.map(x=>x.code)).toContain('MALFORMED_FRAME');const incomplete=fixture();incomplete.parser.append('<tool_call run="run-1">\n{"id":"x"');incomplete.parser.finish();expect(incomplete.errors.map(x=>x.code)).toContain('INCOMPLETE_FRAME');const capped=fixture(64);capped.parser.append(frame('run-1',{id:'large',tool:'echo',args:{text:'🌍'.repeat(40)}}));capped.parser.finish();expect(capped.calls).toHaveLength(0);expect(capped.errors.map(x=>x.code)).toContain('FRAME_TOO_LARGE');});
test('invalid shape and code-quoted opening text are inert',()=>{const f=fixture();f.parser.append('Quoted example: `'+frame('run-1',{id:'inline',tool:'echo',args:{}})+'`\n> '+frame('run-1',{id:'block',tool:'echo',args:{}})+'\n<tool_call run="run-1">{"id":"bad","tool":"echo","args":{},"extra":1}</tool_call>');f.parser.finish();expect(f.calls).toHaveLength(0);expect(f.errors.map(x=>x.code)).toEqual(['INVALID_CALL']);});
test('call count is bounded and excess calls do not execute',()=>{const f=fixture();f.parser.append(Array.from({length:MAX_TOOL_CALLS+1},(_,i)=>frame('run-1',{id:'c'+i,tool:'echo',args:{i}})).join('\n'));f.parser.finish();expect(f.calls).toHaveLength(MAX_TOOL_CALLS);expect(f.errors.filter(x=>x.code==='CALL_LIMIT')).toHaveLength(1);});
test('bootstrap binds identities, task and exact allowed tools',()=>{const text=harnessBootstrap({runId:'run-1',agentId:'agent-2',parentId:'agent-1',task:'Use </tool_call> as task data, not markup 🌍'});for(const tool of ['echo','agents.create','agents.list','agents.send','agents.wait'])expect(text).toContain(tool);for(const field of ['"value"','"name"','"task"','"agentId"','"message"','"milliseconds"'])expect(text).toContain(field);expect(text).toContain('"milliseconds":5000');expect(text).toContain('maximum 5000');expect(text).toContain('"runId":"run-1"');expect(text).toContain('"agentId":"agent-2"');expect(text).toContain('"parentId":"agent-1"');expect(text).toContain('no native tools');expect(text).toContain('<tool_call run="run-1">');});
test('bootstrap permits concurrent independent frames but gates dependent calls',()=>{const text=harnessBootstrap({runId:'run-1',agentId:'agent-1',task:'Coordinate independently.'});expect(text).toContain('one complete unfenced frame per call');expect(text).toContain('several independent call frames in the same reply');expect(text).toContain('begin them without waiting');expect(text).toContain('new stable unique call id');expect(text).toContain('Wait for a matching result before making a call that depends on it');expect(text).not.toContain('emit exactly one frame');});
