import{test,expect}from'bun:test';
import{mkdtempSync,rmSync,readFileSync,writeFileSync,statSync,symlinkSync}from'node:fs';
import{tmpdir}from'node:os';import{join}from'node:path';
import{OperationJournal,shouldJournal}from'../src/chatgpt/receipts.ts';
const account={id:'test',userId:'u',baseURL:'https://chatgpt.com',label:'test',created:'now'};
function fixture(fn:(journal:OperationJournal,root:string)=>void){const root=mkdtempSync(join(tmpdir(),'chatgpt-receipts-'));try{fn(new OperationJournal(account,{directory:root}),root);}finally{rmSync(root,{recursive:true,force:true});}}
test('private pending receipt stores fingerprint without prompts or secrets',()=>fixture((j,root)=>{const r=j.start('chat.send',{text:'PRIVATE PROMPT',authorization:'SECRET'},{requestId:'one'});expect(r.reused).toBe(false);expect(statSync(root).mode&511).toBe(448);expect(statSync(join(root,'one.json')).mode&511).toBe(384);expect(readFileSync(join(root,'one.json'),'utf8')).not.toContain('PRIVATE PROMPT');expect(readFileSync(join(root,'one.json'),'utf8')).not.toContain('SECRET');expect(()=>j.start('chat.send',{authorization:'SECRET',text:'PRIVATE PROMPT'},{requestId:'one'})).toThrow('automatic replay');}));
test('completed request ID returns preserved result and transcription metadata without rerun',()=>fixture((j,root)=>{j.start('dictation.transcribe',{path:'/explicit.wav'},{requestId:'audio'});const result={text:'spoken words',metadata:{asset_pointer:'sediment://file_audio',duration:3}};j.finish('audio',result);const next=new OperationJournal(account,{directory:root}).start('dictation.transcribe',{requestId:'audio',path:'/explicit.wav'});expect(next.reused).toBe(true);expect(next.result).toEqual(result);expect(statSync(join(root,'audio.result.json')).mode&511).toBe(384);expect(j.list().items[0].status).toBe('complete');}));
test('changed arguments and account identity cannot reuse completed request ID',()=>fixture((j,root)=>{j.start('settings.set',{value:'yes'},{requestId:'one'});j.finish('one',{changed:true});expect(()=>j.start('settings.set',{value:'no'},{requestId:'one'})).toThrow('another operation or arguments');const other=new OperationJournal({...account,userId:'other'},{directory:root});expect(()=>other.get('one')).toThrow('another account');}));
test('failure stores only safe classification and permanently blocks automatic reused-ID replay',()=>fixture((j,root)=>{j.start('chat.new',{text:'hello'},{requestId:'one'});j.fail('one',{code:'OUTCOME_UNKNOWN',status:503,message:'PRIVATE TOKEN https://private.invalid/?token=SECRET',action:'UNTRUSTED SERVER'});const raw=readFileSync(join(root,'one.json'),'utf8');expect(raw).not.toContain('SECRET');expect(raw).not.toContain('UNTRUSTED');expect(j.get('one').receipt.status).toBe('unknown');expect(()=>j.start('chat.new',{text:'hello'},{requestId:'one'})).toThrow('automatic replay');}));
test('damaged result is reported and never returned as a deduplicated success',()=>fixture((j,root)=>{j.start('invoices.sync',{}, {requestId:'one'});j.finish('one',{ids:['i']});writeFileSync(join(root,'one.result.json'),'corrupt');expect(()=>j.start('invoices.sync',{}, {requestId:'one'})).toThrow('integrity');expect(j.list().damaged).toEqual(['one.json']);expect(j.list().complete).toBe(false);}));
test('pending receipt from another journal instance blocks replay after process interruption',()=>fixture((j,root)=>{j.start('chat.edit',{message:'m',text:'x'},{requestId:'one'});const restarted=new OperationJournal(account,{directory:root});expect(()=>restarted.start('chat.edit',{message:'m',text:'x'},{requestId:'one'})).toThrow('pending or unknown');}));
test('journal excludes binary and raw reads and refuses unsafe IDs and links',()=>fixture((j,root)=>{for(const op of ['api.request','ui.screenshot','media.download','audio.status','conversations.get'])expect(shouldJournal(op)).toBe(false);expect(()=>j.start('api.request',{})).toThrow('outside');expect(()=>j.start('chat.send',{}, {requestId:'../escape'})).toThrow();writeFileSync(join(root,'target'),'original');symlinkSync(join(root,'target'),join(root,'linked.json'));expect(()=>j.start('chat.send',{}, {requestId:'linked'})).toThrow('Unsafe');expect(readFileSync(join(root,'target'),'utf8')).toBe('original');}));
