import {test,expect} from 'bun:test';
import {setSetting} from '../src/chatgpt/settings.ts';
import type {Actions} from '../src/chatgpt/actions.ts';
function fixture(controls:any[]){
 const calls:any[]=[];let state=controls.map(c=>({...c}));const snap=()=>({epoch:'fresh',controls:state,url:'https://chatgpt.com/',title:'',text:'',messages:[],media:[]});
 const actions={b:{async call(op:string,args:any){calls.push({op,...args});if(args.kind==='fill')state=state.map(c=>c.ref===args.ref?{...c,value:args.text}:c);}},async settings(section:string){calls.push({op:'settings',section});return snap();},async snapshot(){calls.push({op:'snapshot'});return snap();},async press(s:any,c:any){calls.push({op:'press',ref:c.ref,epoch:s.epoch});if(c.role==='switch'||c.role==='checkbox')state=state.map(x=>x.ref===c.ref?{...x,checked:String(c.checked)!=='true'}:x);},async find(predicate:(c:any)=>boolean){const s=snap(),c=s.controls.find(predicate);if(!c)throw new Error('No matching option');return {s,c};},async named(name:string){calls.push({op:'named',name});}};
 return {actions:actions as unknown as Actions,calls};
}
const args={section:'General',name:'Example',value:'true'};
test('already selected setting is a no-op with bounded UI-only receipt',async()=>{const f=fixture([{name:'Example',role:'switch',checked:true,ref:1}]);const r=await setSetting(f.actions,args);expect(r.changed).toBe(false);expect(r.verifiedUI).toBe(true);expect(r.persistence).toContain('not independently verified');expect(f.calls).toEqual([{op:'settings',section:'General'}]);});
test('switch changes once using fresh reference then verifies readback',async()=>{const f=fixture([{name:'Example',role:'switch',checked:false,ref:2}]);const r=await setSetting(f.actions,args);expect(r.changed).toBe(true);expect(r.control.checked).toBe(true);expect(f.calls).toEqual([{op:'settings',section:'General'},{op:'press',ref:2,epoch:'fresh'},{op:'snapshot'}]);});
test('unknown role and invalid switch value perform no click',async()=>{for(const control of [{name:'Example',role:'button',ref:3},{name:'Example',role:'switch',checked:false,ref:3}]){const f=fixture([control]);await expect(setSetting(f.actions,{...args,value:'unsupported'})).rejects.toThrow();expect(f.calls.some(c=>c.op==='press'||c.op==='action'||c.op==='named')).toBe(false);}});
test('missing option opens selector once but makes no selection',async()=>{const f=fixture([{name:'Example',role:'combobox',value:'Current',ref:4}]);await expect(setSetting(f.actions,{...args,value:'Missing'})).rejects.toThrow('No matching option');expect(f.calls.filter(c=>c.op==='press')).toEqual([{op:'press',ref:4,epoch:'fresh'}]);expect(f.calls.some(c=>c.op==='named'||c.op==='action')).toBe(false);});
test('disabled or ambiguous enabled targets are rejected without interaction',async()=>{for(const controls of [[{name:'Example',role:'switch',disabled:true,ref:1}],[{name:'Example',role:'switch',ref:1},{name:'Example',role:'switch',ref:2}]]){const f=fixture(controls);await expect(setSetting(f.actions,args)).rejects.toThrow('exactly one enabled');expect(f.calls).toEqual([{op:'settings',section:'General'}]);}});
test('text fill clicks only an explicitly supplied commit label and reads back',async()=>{for(const commit of [undefined,'Save preferences']){const f=fixture([{name:'Example',tag:'textarea',role:'textbox',value:'before',ref:5}]);const r=await setSetting(f.actions,{...args,value:'after',commit});expect(r.changed).toBe(true);expect(f.calls.filter(c=>c.op==='action')).toEqual([{op:'action',kind:'fill',ref:5,epoch:'fresh',text:'after'}]);expect(f.calls.filter(c=>c.op==='named')).toEqual(commit?[{op:'named',name:commit}]:[]);expect(f.calls.at(-1)).toEqual({op:'snapshot'});}});
test('password and file inputs never fill or commit',async()=>{for(const type of ['password','file']){const f=fixture([{name:'Example',tag:'input',role:'textbox',type,ref:6}]);await expect(setSetting(f.actions,{...args,commit:'Save'})).rejects.toThrow('dedicated website flow');expect(f.calls).toEqual([{op:'settings',section:'General'}]);}});
