import {test,expect} from 'bun:test';
import{mkdtempSync,rmSync,readFileSync,writeFileSync}from'node:fs';
import{join}from'node:path';
import{tmpdir}from'node:os';
import {downloadMedia,listMedia,imageBootstrap,exportMedia,auditMedia,readExportedMedia} from '../src/chatgpt/media.ts';
const url='https://chatgpt.com/backend-api/estuary/content?id=asset&sig=PRIVATE_SIGNATURE';
const png=Buffer.from([137,80,78,71,13,10,26,10,0]);
test('bootstrap returns safe opaque thumbnail reference and honest library gap',async()=>{const r=await imageBootstrap(async()=>({images_count:119,archived_images_count:0,thumbnail_url:url}));expect(r.complete).toBe(false);expect(r.counts.active).toBe(119);expect(r.items.length).toBe(1);expect(JSON.stringify(r)).not.toContain('PRIVATE_SIGNATURE');});
test('exact observed signed URL uses authenticated binary request and verified MIME',async()=>{let called:any[]=[];const r=await downloadMedia(url,async(...args)=>{called=args;return {status:200,contentType:'application/octet-stream',base64:png.toString('base64')};});expect(called).toEqual(['/backend-api/estuary/content?id=asset&sig=PRIVATE_SIGNATURE','GET',undefined,true]);expect(r.extension).toBe('png');expect(r.contentType).toBe('image/png');expect(r.bytes).toEqual(png);expect(JSON.stringify(r.metadata)).not.toContain('PRIVATE_SIGNATURE');});
test('opaque media pointers require explicit observed mappings',async()=>{let reads=0;const request=async()=>{reads++;return {base64:png.toString('base64'),contentType:'image/png'};};await expect(downloadMedia('sediment://opaque',request)).rejects.toThrow('no observed');expect(reads).toBe(0);const r=await downloadMedia('sediment://opaque',request,{observations:[{reference:'sediment://opaque',url}]});expect(r.extension).toBe('png');expect(reads).toBe(1);});
test('rejects arbitrary destinations, auth URLs and unobserved endpoints before request',async()=>{let reads=0;const request=async()=>{reads++;return {};};for(const ref of ['http://127.0.0.1/private','https://evil.example/image','https://chatgpt.com.evil.example/backend-api/estuary/content','https://user:pass@chatgpt.com/backend-api/estuary/content','https://chatgpt.com/backend-api/files/guess','https://chatgpt.com:8443/backend-api/estuary/content'])await expect(downloadMedia(ref,request)).rejects.toThrow();expect(reads).toBe(0);});
test('rejects HTML, missing payload, oversized media and denied responses',async()=>{for(const response of [{base64:Buffer.from('<html>Login</html>').toString('base64'),contentType:'text/html'},{base64:''},{base64:png.toString('base64'),status:403}])await expect(downloadMedia(url,async()=>response)).rejects.toThrow();await expect(downloadMedia(url,async()=>({base64:png.toString('base64')}),{maxBytes:1})).rejects.toThrow('limit');});
test('opaque thumbnail resolves a fresh server URL on download',async()=>{const paths:string[]=[];const r=await downloadMedia('bootstrap-thumbnail',async path=>{paths.push(path);return path==='/backend-api/images/bootstrap'?{thumbnail_url:url}:{base64:png.toString('base64'),contentType:'image/png'};});expect(paths.length).toBe(2);expect(r.extension).toBe('png');});

test('observed file resolver maps archived sediment file IDs to exact returned URL',async()=>{const calls:any[]=[];const r=await downloadMedia('sediment://file_0123456789abcdef',async(...args)=>{calls.push(args);return args[0].startsWith('/backend-api/files/download/')?{status:'success',download_url:url}:{base64:png.toString('base64'),contentType:'image/png'};});expect(calls[0][0]).toBe('/backend-api/files/download/file_0123456789abcdef?inline=true');expect(r.extension).toBe('png');expect(calls.length).toBe(2);});

test('Library All view preserves origins and never schedules external-provider files',async()=>{const root={items:[{id:'own',kind:'file',access_kind:'owned',app_id:'chatgpt-web',file_id:'file_abc',name:'own.png',thumbnail_url:url},{id:'cloud',kind:'file',access_kind:'mounted',app_id:'google_drive',file_id:'cloud-secret',name:'external.pdf'}],cursor:'next-page'};const request=async(path:string)=>path.includes('bootstrap')?{images_count:0,archived_images_count:0}:path.includes('/nodes?')?root:{items:[],cursor:null};const r=await listMedia(request);expect(r.items[0].downloadable).toBe(true);expect(r.items[1].downloadable).toBe(false);expect(r.items[1].reference).toBeUndefined();expect(r.complete).toBe(false);expect(r.coverage[0].complete).toBe(false);expect(JSON.stringify(r)).not.toContain('PRIVATE_SIGNATURE');expect((await listMedia(request,{includeRaw:true})).rawPages?.find(x=>x.scope==='library-root')?.response).toEqual(root);});

test('generated and image-library pagination use observed after and POST cursor with deduplication',async()=>{const paths:string[]=[],bodies:any[]=[];const generated={id:'gen',source:'chatgpt',generation_type:'image_gen',asset_pointer:'sediment://file_image',conversation_id:'chat',is_archived:false};const lib={id:'lib',access_kind:'owned',app_id:'chatgpt-web',file_id:'file_image'};const r=await listMedia(async(path,method,body)=>{paths.push(path);bodies.push(body);if(path.includes('bootstrap'))return{images_count:1,archived_images_count:0};if(path.includes('/nodes?'))return{items:[],cursor:null};if(path.includes('uploaded_images'))return {items:[]};if(path.includes('image_gen'))return path.includes('&after=')?{items:[],cursor:null}:{items:[generated],cursor:'gen-next'};return body.cursor?{items:[],cursor:null}:{items:[lib],cursor:'lib-next'};});expect(paths).toContain('/backend-api/my/recent/image_gen?limit=25&after=gen-next');expect(bodies).toContainEqual({limit:20,cursor:'lib-next',categories:['image'],include_saved_entities:true});expect(r.items.filter(x=>x.downloadable).length).toBe(1);expect(r.coverage.find(x=>x.scope==='media:generated-images')?.complete).toBe(true);});
test('raw catalog records bootstrap and exact page cursor/time provenance',async()=>{const r=await listMedia(async path=>path.includes('bootstrap')?{images_count:1,archived_images_count:0,marker:'bootstrap'}:path.includes('/nodes?')?(path.includes('&cursor=')?{items:[],cursor:null}:{items:[],cursor:'root-next'}):{items:[],cursor:null},{includeRaw:true});const raw=r.rawPages!;expect(raw[0].scope).toBe('images-bootstrap');expect(raw[0].response.marker).toBe('bootstrap');expect(raw.filter(x=>x.scope==='library-root').map(x=>x.cursorIn)).toEqual([null,'root-next']);for(const page of raw){expect(new Date(page.requestStartedAt).toISOString()).toBe(page.requestStartedAt);expect(new Date(page.capturedAt).toISOString()).toBe(page.capturedAt);expect(Date.parse(page.capturedAt)).toBeGreaterThanOrEqual(Date.parse(page.requestStartedAt));}});
test('All-node pagination uses observed cursor query and leaves exposed folders incomplete',async()=>{const paths:string[]=[];const r=await listMedia(async path=>{paths.push(path);if(path.includes('bootstrap'))return{images_count:0,archived_images_count:0};if(path.includes('/nodes?'))return path.includes('&cursor=')?{items:[{id:'folder',kind:'directory',access_kind:'owned',app_id:'chatgpt-web'}],cursor:null}:{items:[{id:'a',kind:'file',access_kind:'owned',app_id:'chatgpt-web',file_id:'file_a'}],cursor:'root-next'};return{items:[],cursor:null};});expect(paths.some(p=>p.endsWith('&cursor=root-next'))).toBe(true);expect(r.coverage.find(x=>x.scope==='media:library-root')?.complete).toBe(true);expect(r.coverage.find(x=>x.scope==='media:library-folders')?.complete).toBe(false);expect(r.complete).toBe(false);});
test('bootstrap count mismatch cannot claim generated-image completeness',async()=>{const r=await listMedia(async path=>path.includes('bootstrap')?{images_count:2,archived_images_count:1}:{items:[],cursor:null});expect(r.complete).toBe(false);expect(r.coverage.find(x=>x.scope==='media:generated-images')?.complete).toBe(true);expect(r.coverage.find(x=>x.scope==='media:image-count-reconciliation')?.complete).toBe(false);expect(r.coverage.find(x=>x.scope==='media:archived-images')?.complete).toBe(false);});

async function exportFixture(fn:(output:string)=>Promise<void>){const output=mkdtempSync(join(tmpdir(),'media-export-'));try{await fn(output);}finally{rmSync(output,{recursive:true,force:true});}}
const captured={items:[{id:'one',reference:'sediment://file_one',downloadable:true},{id:'external',reference:'cloud-resource',downloadable:false}],coverage:[],complete:true};
test('media export resumes hashes, repairs corruption and leaves external files untouched',()=>exportFixture(async output=>{const calls:string[]=[];const request=async(path:string)=>{calls.push(path);return path.includes('/files/download/')?{status:'success',download_url:url}:{base64:png.toString('base64'),contentType:'image/png'};};const opts={output,accountId:'test',userId:'user'};const first=await exportMedia(captured,request,opts);expect(first.complete).toBe(true);expect(first.files).toBe(1);expect(readExportedMedia(output,'sediment://file_one',{accountId:'test',userId:'user'})?.bytes).toEqual(png);expect(readExportedMedia(output,'sediment://file_one',{accountId:'other',userId:'user'})).toBeUndefined();expect(calls.length).toBe(2);await exportMedia(captured,request,opts);expect(calls.length).toBe(2);const m=JSON.parse(readFileSync(join(output,'media-manifest.json'),'utf8'));const e:any=Object.values(m.entries)[0];writeFileSync(join(output,e.file),'corrupt');expect(auditMedia(output).integrity).toBe(false);await exportMedia(captured,request,opts);expect(calls.length).toBe(4);expect(auditMedia(output).integrity).toBe(true);expect(calls.some(p=>p.includes('cloud-resource'))).toBe(false);}));
test('media export stops immediately on429 and resumes without claiming completeness',()=>exportFixture(async output=>{let reads=0;const r=await exportMedia({...captured,items:[...captured.items,{id:'two',reference:'sediment://file_two',downloadable:true}]},async()=>{reads++;throw Object.assign(new Error('429 private secret'),{status:429});},{output,accountId:'test'});expect(reads).toBe(1);expect(r.paused).toBe(true);expect(r.complete).toBe(false);expect(JSON.stringify(r)).not.toContain('private secret');expect(readFileSync(join(output,'media-manifest.json'),'utf8')).not.toContain('private secret');}));
test('media export rejects account mixing',()=>exportFixture(async output=>{await exportMedia({items:[],coverage:[],complete:true},async()=>({}),{output,accountId:'one'});await expect(exportMedia({items:[]},async()=>({}),{output,accountId:'two'})).rejects.toThrow('identity');}));
test('legacy app-null owned sediment files remain downloadable',async()=>{const r=await listMedia(async path=>path.includes('bootstrap')?{images_count:0,archived_images_count:0}:path.includes('/nodes?')?{items:[{id:'legacy',kind:'file',access_kind:'owned',app_id:null,file_id:'file_legacy'}],cursor:null}:{items:[],cursor:null});expect(r.items[0].downloadable).toBe(true);expect(r.items[0].origin.appId).toBeNull();});
test('media accepts native service bytes without a base64 transport frame',async()=>{const r=await downloadMedia(url,async()=>({bytes:png,contentType:'image/png',status:200}));expect(r.bytes).toEqual(png);expect(r.extension).toBe('png');});

test('explicit owned catalog MIME permits HTML documents while failures keep safe structured causes',()=>exportFixture(async output=>{const html=Buffer.from('<html>saved document</html>');const r=await exportMedia({items:[{id:'html',reference:'sediment://file_html',downloadable:true,mimeType:'text/html'}],complete:true,coverage:[]},async path=>path.includes('/files/download/')?{status:'success',download_url:url}:{bytes:html,contentType:'text/html'},{output,accountId:'test'});expect(r.downloadComplete).toBe(true);expect(readExportedMedia(output,'sediment://file_html',{accountId:'test'})?.extension).toBe('html');await exportMedia(captured,async()=>{throw Object.assign(new Error('429 signed PRIVATE_SIGNATURE'),{status:429});},{output,accountId:'test'});const m=JSON.parse(readFileSync(join(output,'media-manifest.json'),'utf8'));const failure:any=Object.values(m.failures)[0];expect(failure.code).toBe('RATE_LIMIT');expect(failure.httpStatus).toBe(429);expect(JSON.stringify(m.failures)).not.toContain('PRIVATE_SIGNATURE');}));
test('images-app uploaded IDs expand binaries while bootstrap counts gallery rows',async()=>{const generated={id:'gen',source:'chatgpt',generation_type:'image_gen',asset_pointer:'sediment://file_shared',is_archived:false};const uploaded={items:[{file_id:'file_shared',timestamp:1},{file_id:'file_extra',timestamp:2}]};const r=await listMedia(async path=>path.includes('bootstrap')?{images_count:3,archived_images_count:0}:path.includes('uploaded_images')?uploaded:path.includes('image_gen')?{items:[generated],cursor:null}:{items:[],cursor:null},{includeRaw:true});expect(r.items.map(x=>x.reference).sort()).toEqual(['sediment://file_extra','sediment://file_shared']);expect(r.counts.enumeratedGalleryRows).toBe(3);expect(r.counts.enumeratedImageUnion).toBe(2);expect(r.coverage.find(x=>x.scope==='media:image-count-reconciliation')?.complete).toBe(true);expect(r.rawPages?.find(x=>x.scope==='images-app-uploads')?.response).toEqual(uploaded);expect(r.globalComplete).toBe(false);});
test('full uploaded pages stop explicitly until continuation is observed',async()=>{const paths:string[]=[];const r=await listMedia(async path=>{paths.push(path);return path.includes('bootstrap')?{images_count:25,archived_images_count:0}:path.includes('uploaded_images')?{items:Array.from({length:25},(_,i)=>({file_id:'file_'+i}))}:{items:[],cursor:null};});expect(paths.filter(x=>x.includes('uploaded_images'))).toEqual(['/backend-api/my/recent/uploaded_images?limit=25&images_app_only=true']);expect(r.coverage.find(x=>x.scope==='media:images-app-uploads')?.complete).toBe(false);expect(r.complete).toBe(false);});
