import {test,expect} from 'bun:test';
import {gptCatalogPath,normalizeGPTCatalog,fetchGPTCatalog} from '../src/chatgpt/gpts';
const cut=(id:string,cursor:any=null)=>({info:{id,title:id},list:{cursor,items:[{resource:{gizmo:{id:'g-fixture',display:{name:'Fixture'},author:{display_name:'Example',user_email:'private@example.invalid'},instructions:'private',short_url:'g-fixture-test'}}}]}});
test('only observed catalog routes and bounded query values execute',()=>{expect(gptCatalogPath({scope:'owned'})).toBe('/public-api/gizmos/discovery/mine?limit=20');expect(gptCatalogPath({scope:'trending',cursor:'6',locale:'en'})).toContain('cursor=6');expect(()=>gptCatalogPath({scope:'unknown'} as any)).toThrow();expect(()=>gptCatalogPath({scope:'owned',cursor:'../secret'})).toThrow();expect(()=>gptCatalogPath({limit:5})).toThrow();});
test('catalog normalizes public fields and retains pagination uncertainty',()=>{const out=normalizeGPTCatalog({cuts:[cut('trending','6'),cut('featured')]});expect(out.items.length).toBe(1);expect(out.cuts[0].pageComplete).toBe(false);expect(out.complete).toBe(false);expect(JSON.stringify(out)).not.toContain('private');expect(out.cuts[1].paginationSupported).toBe(false);});
test('empty owned response is not conflated with global completeness',async()=>{let path='';const out=await fetchGPTCatalog(async p=>{path=p;return {info:{id:'mine',title:'My GPTs'},list:{items:[],cursor:null}}},{scope:'owned'});expect(path).toContain('/mine');expect(out.items).toEqual([]);expect(out.coverage.scopeComplete).toBe(true);expect(out.complete).toBe(true);expect(out.globalComplete).toBe(false);expect(()=>normalizeGPTCatalog({items:[]})).toThrow();});

test('pagination preserves raw receipts and deduplicates aggregate items',async()=>{let calls=0;const out=await fetchGPTCatalog(async()=>{calls++;return cut('mine',calls===1?'20':null)},{scope:'owned',includeRaw:true});expect(calls).toBe(2);expect(out.complete).toBe(true);expect(out.items.length).toBe(1);expect(out.rawPages?.length).toBe(2);});
test('repeated cursors stop boundedly and cannot claim completeness',async()=>{let calls=0;const out=await fetchGPTCatalog(async()=>{calls++;return cut('trending','6')},{scope:'trending'});expect(calls).toBe(2);expect(out.complete).toBe(false);expect(out.coverage.reason).toContain('Repeated cursor');});
