import {test,expect} from 'bun:test';
import {mkdtempSync,writeFileSync,rmSync,readFileSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';
import {runFlow,flowStatus,validateFlow,type Flow} from '../src/chatgpt/flows.ts';import {accountDir,type Account} from '../src/chatgpt/accounts.ts';
async function fixture(fn:(x:any)=>Promise<void>){const dir=mkdtempSync(join(tmpdir(),'flow-test-')),a:Account={id:'flow-test-'+crypto.randomUUID(),label:'fixture',baseURL:'https://chatgpt.com',created:'',userId:'fixture'},path=join(dir,'flow.json');const save=(steps:any[],version=1)=>writeFileSync(path,JSON.stringify({id:'flow',version,steps}));try{await fn({a,path,save});}finally{rmSync(dir,{recursive:true,force:true});rmSync(accountDir(a),{recursive:true,force:true});}}
const shot=(text='')=>({epoch:crypto.randomUUID(),text,url:'https://chatgpt.com/',controls:[{ref:4,name:'Send',role:'button'},{ref:5,name:'Message',role:'textbox'}]});
const click={id:'send',op:'click',args:{target:{name:'Send',role:'button'}}};
test('dry run validates without browser calls or exposed fill text',()=>fixture(async({a,path,save})=>{save([{id:'fill',op:'fill',args:{target:{name:'Message'},text:'private-secret'}}]);const r=await runFlow({call:async()=>{throw Error('must not call')}},a,{path,dryRun:true});expect(r.dryRun).toBe(true);expect(JSON.stringify(r)).not.toContain('private-secret');}));
test('ambiguous write stops and resume refuses automatic replay',()=>fixture(async({a,path,save})=>{save([click,{id:'later',op:'snapshot'}]);let writes=0;const events:any[]=[];const b={call:async(op:string)=>{if(op==='snapshot')return shot();writes++;throw Error('timeout private-secret');}};await expect(runFlow(b,a,{path,runId:'ambiguous'},e=>events.push(e))).rejects.toMatchObject({code:'NEEDS_RECONCILIATION'});await expect(runFlow(b,a,{path,runId:'ambiguous',resume:true})).rejects.toMatchObject({code:'NEEDS_RECONCILIATION'});expect(writes).toBe(1);expect(JSON.stringify(events)+JSON.stringify(flowStatus(a,'ambiguous'))).not.toContain('private-secret');expect(flowStatus(a,'ambiguous').steps).toHaveLength(1);}));
test('resume reconciles uncertain write with explicit proof and skips completed steps',()=>fixture(async({a,path,save})=>{save([{id:'read',op:'snapshot'},{...click,expect:{textIncludes:'Done'}},{id:'last',op:'wait',args:{ms:0}}]);let done=false,writes=0;const b={call:async(op:string)=>{if(op==='snapshot')return shot(done?'Done':'');writes++;done=true;throw Error('unknown');}};await expect(runFlow(b,a,{path,runId:'proof'})).rejects.toMatchObject({code:'NEEDS_RECONCILIATION'});const result=await runFlow(b,a,{path,runId:'proof',resume:true});expect(result.status).toBe('complete');expect(writes).toBe(1);expect(flowStatus(a,'proof').steps[1].proof).toBe('postcondition');expect((await runFlow(b,a,{path,runId:'proof',resume:true})).completed).toBe(3);expect(writes).toBe(1);}));
test('hotloaded pending steps take effect while completed fingerprints remain fixed',()=>fixture(async({a,path,save})=>{const first={id:'first',op:'snapshot'};save([first,{id:'second',op:'key',args:{key:'Enter'}}]);const seen:string[]=[];let once=false;const b={call:async(op:string,args:any)=>{if(op==='snapshot'&&!once){once=true;save([first,{id:'second',op:'key',args:{key:'Escape'}}],2);}if(op==='key')seen.push(args.key);return shot();}};await runFlow(b,a,{path,runId:'hot'});expect(seen).toEqual(['Escape']);save([{id:'first',op:'wait',args:{ms:0}},{id:'second',op:'key',args:{key:'Escape'}}],3);await expect(runFlow(b,a,{path,runId:'hot',resume:true})).rejects.toMatchObject({code:'FLOW_CHANGED'});}));
test('semantic controls use fresh epoch and reject ambiguity before mutation',()=>fixture(async({a,path,save})=>{save([click]);let writes=0;await expect(runFlow({call:async()=>({...shot(),controls:[{ref:1,name:'Send',role:'button'},{ref:2,name:'Send',role:'button'}]})},a,{path,runId:'multiple'})).rejects.toMatchObject({code:'TARGET_UNAVAILABLE'});const b={call:async(op:string,args:any)=>{if(op==='snapshot')return {...shot(),epoch:'fresh'};writes++;expect(args.epoch).toBe('fresh');expect(args.ref).toBe(4);return {};}};await runFlow(b,a,{path,runId:'fresh'});expect(writes).toBe(1);}));
test('failed read can resume, duplicate request id cannot run again',()=>fixture(async({a,path,save})=>{save([{id:'read',op:'snapshot'}]);await expect(runFlow({call:async()=>{throw Error('read failure')}},a,{path,runId:'read'})).rejects.toMatchObject({code:'BROWSER_OPERATION_FAILED'});await expect(runFlow({call:async()=>shot()},a,{path,runId:'read'})).rejects.toMatchObject({code:'RUN_EXISTS'});expect((await runFlow({call:async()=>shot()},a,{path,runId:'read',resume:true})).status).toBe('complete');}));
test('schema rejects arbitrary code, stale refs, unsafe paths, and missing identifiers',()=>{for(const steps of [[{id:'s',op:'eval',args:{code:'evil'}}],[{id:'s',op:'click',args:{ref:1,epoch:'old'}}],[{id:'s',op:'upload',args:{files:['/tmp/../secret']}}],[{op:'snapshot'}]])expect(()=>validateFlow({id:'flow',version:1,steps})).toThrow();expect(()=>validateFlow({version:1,steps:[{id:'s',op:'snapshot'}]})).toThrow();});
test('timeout records unknown and does not leak the browser outcome',()=>fixture(async({a,path,save})=>{save([{...click,args:{...click.args,timeoutMs:10}}]);const b={call:async(op:string)=>op==='snapshot'?shot():new Promise(()=>{})};await expect(runFlow(b,a,{path,runId:'timeout'})).rejects.toMatchObject({code:'NEEDS_RECONCILIATION'});expect(flowStatus(a,'timeout').steps[0].status).toBe('unknown');}));
test('canonical fingerprints tolerate JSON property reordering',()=>fixture(async({a,path,save})=>{save([click]);const b={call:async()=>shot()};await runFlow(b,a,{path,runId:'canonical'});save([{args:{target:{role:'button',name:'Send'}},op:'click',id:'send'}]);expect((await runFlow(b,a,{path,runId:'canonical',resume:true})).status).toBe('complete');}));
test('concurrent request ownership is exclusive and dead-owner locks can resume',()=>fixture(async({a,path,save})=>{save([{id:'read',op:'snapshot'}]);let release:(x:any)=>void=()=>{};const first=runFlow({call:()=>new Promise(r=>{release=r;})},a,{path,runId:'locked'});await expect(runFlow({call:async()=>shot()},a,{path,runId:'locked',resume:true})).rejects.toMatchObject({code:'RUN_BUSY'});release(shot());await first;const lock=join(accountDir(a),'flows','locked.json.lock');writeFileSync(lock,JSON.stringify({pid:2147483647}));expect((await runFlow({call:async()=>shot()},a,{path,runId:'locked',resume:true})).status).toBe('complete');}));
