import{test,expect}from'bun:test';
import{ConversationActions}from'../src/chatgpt/conversation-actions.ts';
function fixture(options:{duplicate?:boolean;missing?:boolean;stuck?:boolean}={}){let title='Integration',pinned=false,menu=false,editing=false,hovered=false,typed='',epoch=0,archived=false,archiveDialog=false;const calls:any[]=[];const snapshot=()=>{epoch++;if(archiveDialog)return {epoch:String(epoch),text:archived?'Archived chats':'You have no archived conversations.',controls:archived?[{ref:1,href:'/c/test-id',name:title},{ref:11,name:'Unarchive conversation '+title}]:[{ref:0,name:'Close'}]};const controls:any[]=options.missing?[]:[{ref:1,href:'/c/test-id',name:title+(pinned?', pinned conversation':'')}];if(options.duplicate)controls.push({ref:10,href:'/c/other',name:title});if(hovered)controls.push({ref:2,name:'Open conversation options for '+title});if(menu)for(const [i,name]of ['Rename',pinned?'Unpin chat':'Pin chat','Archive','Share'].entries())controls.push({ref:3+i,name,role:'menuitem'});if(editing)controls.push({ref:9,name:'Chat title',tag:'input',value:title});return {epoch:String(epoch),controls};};const browser={async call(op:string,args:any={}){calls.push({op,...args});if(op==='snapshot')return snapshot();if(op==='surface.open'){archiveDialog=false;return{};}if(op==='surface.close')return{};if(op==='hover'){hovered=true;return{};}if(op==='key'){if(args.key==='Enter'&&editing){if(!options.stuck)title=typed;editing=false;}menu=false;return{};}if(op==='action'){expect(args.epoch).toBe(String(epoch));if(args.kind==='fill'){typed=args.text;return{};}if(args.ref===2)menu=true;if(args.ref===3){editing=true;menu=false;}if(args.ref===4){pinned=!pinned;menu=false;}if(args.ref===5){archived=true;menu=false;}if(args.ref===11)archived=false;return{};}return{};}};return{calls,a:new ConversationActions(browser,'fixture',{attempts:2,delayMs:0}),archiveDialog:()=>{archiveDialog=true;},state:()=>({title,pinned,archived})};}
test('rename commits once and verifies exact target row',async()=>{const f=fixture();const r=await f.a.manage('rename',{id:'test-id',title:'Renamed'});expect(r.changed).toBe(true);expect(f.state().title).toBe('Renamed');expect(f.calls.filter(c=>c.kind==='fill').length).toBe(1);expect(f.calls.filter(c=>c.key==='Enter').length).toBe(1);expect(f.calls.every(c=>c.surface==='fixture')).toBe(true);});
test('pin and unpin verify inverse menu with pinned aria label suffix',async()=>{const f=fixture();expect((await f.a.manage('pin',{id:'test-id'})).changed).toBe(true);expect(f.state().pinned).toBe(true);expect((await f.a.manage('unpin',{id:'test-id'})).changed).toBe(true);expect(f.state().pinned).toBe(false);});
test('already requested rename and pin state are no-ops',async()=>{const f=fixture();expect((await f.a.manage('rename',{id:'test-id',title:'Integration'})).changed).toBe(false);expect((await f.a.manage('unpin',{id:'test-id'})).changed).toBe(false);expect(f.calls.filter(c=>c.kind==='fill'||c.ref===4).length).toBe(0);});
test('missing or ambiguous row titles cause no clicks',async()=>{for(const option of [{missing:true},{duplicate:true}]){const f=fixture(option);await expect(f.a.manage('rename',{id:'test-id',title:'Renamed'})).rejects.toThrow();expect(f.calls.filter(c=>c.op==='action').length).toBe(0);}});
test('unobserved unshare flow fail before any browser operation',async()=>{const f=fixture();for(const action of ['unshare'] as const)await expect(f.a.manage(action,{id:'test-id'})).rejects.toThrow('Unsupported');expect(f.calls.length).toBe(0);});
test('unknown rename outcome never replays commit',async()=>{const f=fixture({stuck:true});await expect(f.a.manage('rename',{id:'test-id',title:'Renamed'})).rejects.toMatchObject({code:'UNKNOWN_OUTCOME'});expect(f.calls.filter(c=>c.kind==='fill').length).toBe(1);expect(f.calls.filter(c=>c.key==='Enter').length).toBe(1);});
test('sharing opens observed dialog without claiming a shared link',async()=>{const f=fixture();const r=await f.a.manage('share',{id:'test-id'});expect(r).toMatchObject({stage:'share-launcher-clicked',shared:false,complete:false});expect(f.calls.filter(c=>c.op==='action').map(c=>c.ref)).toEqual([2,6]);});
test('archive and restore verify exact archived row and refreshed active sidebar',async()=>{const f=fixture();f.a.archived=async()=>{f.archiveDialog();return {} as any;};expect(await f.a.manage('archive',{id:'test-id'})).toMatchObject({state:'archived',verifiedUI:true});expect(f.state().archived).toBe(true);expect(await f.a.manage('unarchive',{id:'test-id'})).toMatchObject({changed:true,verifiedUI:true});expect(f.state().archived).toBe(false);expect(f.calls.filter(c=>c.op==='action'&&c.ref===5).length).toBe(1);expect(f.calls.filter(c=>c.op==='action'&&c.ref===11).length).toBe(1);expect(f.calls.filter(c=>c.op==='surface.open').length).toBe(1);});

test('empty archive dialog is a read-only receipt and never proves restoration',async()=>{const calls:any[]=[];const a=new ConversationActions({async call(op,args){calls.push({op,args});return {epoch:'one',text:'Archived chats\nYou have no archived conversations.',controls:[{ref:0,name:'Close'}]};}},'fixture');const r=await a.archived();expect(r).toMatchObject({empty:true,complete:false,restoreFlowVerified:false,items:[]});expect(calls.map(c=>c.op)).toEqual(['snapshot']);});
