import {test,expect} from 'bun:test';
import {timestampISO,messageTime,messageTimeLabel,localMessageTime} from '../src/chatgpt/message-time.ts';
import {reconcileMessages} from '../src/chatgpt/tui-delivery.ts';
const first='2026-09-15T12:34:56.000Z',later='2026-09-15T13:00:00.000Z';
test('server epoch seconds, milliseconds and timezone-qualified timestamps normalize identically',()=>{const ms=Date.parse(first);for(const raw of [ms,ms/1000,String(ms/1000),first,'2026-09-15T15:34:56+03:00'])expect(timestampISO(raw)).toBe(first);for(const raw of [null,undefined,'',NaN,Infinity,{},'yesterday','2026-09-15'])expect(timestampISO(raw)).toBeUndefined();expect(messageTime({create_time:ms/1000})).toEqual({timestamp:first,timestampSource:'website'});});
test('polling and reconciliation preserve a local timestamp until a website creation time is available',()=>{const local={id:'user',role:'user',text:'hello',...localMessageTime(first)};const firstRead=reconcileMessages([local],[{id:'user',role:'user',text:'hello',firstObservedAt:later}])[0];expect(firstRead.timestamp).toBe(first);expect(firstRead.timestampSource).toBe('local');const real=reconcileMessages([firstRead],[{id:'user',role:'user',text:'hello',create_time:Date.parse(first)/1000-10}])[0];expect(real.timestamp).toBe('2026-09-15T12:34:46.000Z');expect(real.timestampSource).toBe('website');expect(reconcileMessages([real],[{id:'user',role:'user',text:'hello'}])[0].timestamp).toBe(real.timestamp);});
test('legacy and DOM observations are labeled as observation times instead of invented creation times',()=>{const old=messageTime({},undefined,first);expect(old).toEqual({timestamp:first,timestampSource:'observed'});expect(messageTime({},old,later)).toEqual(old);expect(messageTime({firstObservedAt:first},undefined,later)).toEqual(old);expect(messageTimeLabel(old,'UTC')).toContain('2026-09-15 12:34:56');expect(messageTimeLabel(old,'UTC')).toContain('seen');expect(messageTimeLabel(localMessageTime(first),'UTC')).toContain('local');expect(messageTimeLabel({create_time:Date.parse(first)/1000},'UTC')).not.toContain('seen');});
test('time labels include the historical local date and timezone offset',()=>{expect(messageTimeLabel({timestamp:first,timestampSource:'website'},'Asia/Jerusalem')).toContain('2026-09-15 15:34:56');expect(messageTimeLabel({timestamp:first,timestampSource:'website'},'Asia/Jerusalem')).toContain('GMT+3');});

test('DOM identity promotion retains the first displayed time and confirmed attachments',()=>{const previous=[{id:'dom:conversation-turn-2',domTurnId:'conversation-turn-2',role:'assistant',text:'partial',...messageTime({},undefined,first)},{id:'user',role:'user',text:'file',files:['/tmp/fixture.txt'],...localMessageTime(first)}];const current=reconcileMessages(previous,[{id:'server-id',domTurnId:'conversation-turn-2',role:'assistant',text:'complete',firstObservedAt:later},{id:'user',role:'user',text:'file'}]);expect(current).toHaveLength(2);expect(current.find(m=>m.id==='server-id')?.timestamp).toBe(first);expect(current.find(m=>m.id==='user')?.files).toEqual(['/tmp/fixture.txt']);});
