import {createHash,randomUUID} from 'node:crypto';
import {existsSync,lstatSync,openSync,closeSync,writeFileSync,readFileSync,fsyncSync,readdirSync,chmodSync} from 'node:fs';
import {join,resolve} from 'node:path';
import {accountDir,atomicJSON,privateDir,validId,type Account} from './accounts.ts';
const operations=new Set(['chat.new','chat.send','chat.edit','chat.branch','chat.regenerate','conversations.rename','conversations.pin','conversations.unpin','conversations.archive','conversations.unarchive','conversations.share','conversations.unshare','settings.set','dictation.transcribe','invoices.download','invoices.sync']);
export const shouldJournal=(operation:string)=>operations.has(operation);
const sha=(value:string)=>createHash('sha256').update(value).digest('hex');
const canonical=(v:any):any=>Array.isArray(v)?v.map(canonical):v&&typeof v==='object'?Object.fromEntries(Object.keys(v).sort().filter(k=>v[k]!==undefined).map(k=>[k,canonical(v[k])])):v;
const fault=(code:string,message:string,id?:string)=>Object.assign(new Error(message),{code,requestId:id,action:'Inspect the local receipt and current website state before another attempt.'});
export type OperationReceipt={schema:1;id:string;account:{id:string;userId?:string;workspace?:string};operation:string;argsFingerprint:string;status:'pending'|'complete'|'unknown'|'not-submitted';started:string;updated:string;result?:{file:string;sha256:string;bytes:number};error?:{code:string;httpStatus?:number;outcome:'unknown'|'not-submitted';action:string}};
/** Local request-ID replay guard; no claim of remote exactly-once execution. */
export class OperationJournal {
 readonly root:string;
 constructor(private account:Account,options:{directory?:string}={}){this.root=resolve(options.directory||join(accountDir(account),'operation-receipts'));if(existsSync(this.root)&&lstatSync(this.root).isSymbolicLink())throw new Error('Unsafe receipt directory.');privateDir(this.root);chmodSync(this.root,0o700);}
 private path(id:string,suffix='.json'){validId(id);const p=join(this.root,id+suffix);if(existsSync(p)&&lstatSync(p).isSymbolicLink())throw new Error('Unsafe receipt file.');return p;}
 private assertAccount(receipt:OperationReceipt){if(receipt.schema!==1||receipt.account.id!==this.account.id||receipt.account.userId!==this.account.userId||receipt.account.workspace!==this.account.workspace)throw fault('ACCOUNT_MISMATCH','Operation receipt belongs to another account.');}
 get(id:string):{receipt:OperationReceipt;result?:any}{const receipt=JSON.parse(readFileSync(this.path(id),'utf8')) as OperationReceipt;this.assertAccount(receipt);if(receipt.id!==id)throw fault('RECEIPT_CORRUPT','Operation receipt identity is inconsistent.',id);if(receipt.status!=='complete')return {receipt};if(!receipt.result||receipt.result.file!==id+'.result.json')throw fault('RECEIPT_CORRUPT','Completed operation lacks its result.',id);const bytes=readFileSync(this.path(id,'.result.json'));if(bytes.length!==receipt.result.bytes||sha(bytes.toString())!==receipt.result.sha256)throw fault('RECEIPT_CORRUPT','Saved operation result failed integrity verification.',id);return {receipt,result:JSON.parse(bytes.toString())};}
 list(options:{limit?:number}={}){const items:OperationReceipt[]=[],damaged:string[]=[];for(const file of readdirSync(this.root).filter(f=>f.endsWith('.json')&&!f.endsWith('.result.json'))){try{items.push(this.get(file.slice(0,-5)).receipt);}catch{damaged.push(file);}}items.sort((a,b)=>b.started.localeCompare(a.started));return {items:items.slice(0,Math.max(1,Math.min(1000,options.limit??100))),total:items.length,damaged,complete:damaged.length===0&&items.length<=(options.limit??100)};}
 start(operation:string,args:any={},options:{requestId?:string}={}):{id:string;reused:boolean;receipt:OperationReceipt;result?:any}{
  if(!shouldJournal(operation))throw new Error('Operation is outside the high-level receipt journal.');
  const id=options.requestId||args.requestId||randomUUID();validId(id);const fingerprint=sha(JSON.stringify(canonical(Object.fromEntries(Object.entries(args).filter(([k])=>k!=='requestId'&&k!=='_signal'))))),path=this.path(id),at=new Date().toISOString();
  const receipt:OperationReceipt={schema:1,id,account:{id:this.account.id,userId:this.account.userId,workspace:this.account.workspace},operation,argsFingerprint:fingerprint,status:'pending',started:at,updated:at};
  let fd:number;try{fd=openSync(path,'wx',0o600);}catch(e){if((e as any).code!=='EEXIST')throw e;const prior=this.get(id);if(prior.receipt.operation!==operation||prior.receipt.argsFingerprint!==fingerprint)throw fault('REQUEST_ID_MISMATCH','Request ID was already used with another operation or arguments.',id);if(prior.receipt.status!=='complete')throw fault('NEEDS_RECONCILIATION','Request ID has a pending or unknown attempt; automatic replay is blocked.',id);return {id,reused:true,...prior};}
  try{writeFileSync(fd,JSON.stringify(receipt,null,2)+'\n');fsyncSync(fd);}finally{closeSync(fd);}
  return {id,reused:false,receipt};
 }
 finish(id:string,result:any){const {receipt}=this.get(id);if(receipt.status!=='pending')throw fault('RECEIPT_FINALIZED','Operation receipt is already finalized or uncertain.',id);const value=result===undefined?null:result,serialized=JSON.stringify(value,null,2)+'\n';// Write result before completion; a crash between them leaves replay blocked.
  atomicJSON(this.path(id,'.result.json'),value);receipt.result={file:id+'.result.json',sha256:sha(serialized),bytes:Buffer.byteLength(serialized)};receipt.status='complete';receipt.updated=new Date().toISOString();atomicJSON(this.path(id),receipt);return {receipt,result:value};
 }
 fail(id:string,error:any){const {receipt}=this.get(id);if(receipt.status==='complete')return {receipt};if(receipt.status!=='pending')return {receipt};const known=new Set(['NOT_SUBMITTED','AUTH_REQUIRED','SITE_CHECK_REQUIRED','RATE_LIMITED','UPSTREAM_UNAVAILABLE','SITE_DRIFT','OUTCOME_UNKNOWN','UNKNOWN_OUTCOME','ACCOUNT_MISMATCH','OPERATION_FAILED']);const code=known.has(error?.code)?error.code:'OPERATION_FAILED';receipt.status=error?.code==='NOT_SUBMITTED'?'not-submitted':'unknown';receipt.updated=new Date().toISOString();receipt.error={code,...(Number.isInteger(error?.status)&&error.status>=100&&error.status<=599?{httpStatus:error.status}:{}),outcome:receipt.status==='not-submitted'?'not-submitted':'unknown',action:receipt.status==='not-submitted'?'No submission was attempted. Fix the preparation failure and use a new request ID for an explicit retry.':'Inspect this receipt and the existing website object before another attempt. No automatic write replay is allowed.'};atomicJSON(this.path(id),receipt);return {receipt};}
}
