import {createHash} from 'node:crypto';
import type {Actions,Snapshot} from './actions.ts';
export function settingsContract(c:any){const name=String(c.name||'');if(name==='Change key sequence')return {kind:'open-options',evidence:'observed-control',replay:'read-only'};if(name==='Press the new key sequence')return {kind:'write',evidence:'requires-fixture',replay:'never'};if(c.role==='switch'||c.role==='checkbox'||c.role==='menuitemcheckbox'||c.role==='radio'||/^(Confirm|Delete|Reset|Archive all|Restore defaults|Cancel plan|Add new|Enroll|Turn on|Set up MFA)/i.test(name))return {kind:'write',evidence:'requires-fixture',replay:'never'};if(c.role==='combobox'||c.role==='menuitemradio'||c.role==='option')return {kind:c.role==='combobox'?'open-options':'write',evidence:c.role==='combobox'?'observed-control':'requires-fixture',replay:c.role==='combobox'?'read-only':'never'};if(c.tag==='button'||c.role==='button')return {kind:'write',evidence:'requires-fixture',replay:'never'};return {kind:'inspect',evidence:'observed-control',replay:'read-only'};}
const allowed:Record<string,RegExp>={Notifications:/^(Codex|Group chats|Health|Library|Marketing|Personalized tips|Projects|Responses|Tasks|Usage) (Push|Email)/,'Cloud browser':/^(Default permissions$|Cookies)/,'Security and login':/^Active sessions/,'Account':/^Select a domain$/,General:/^(Appearance|Contrast|Accent color|Language)$/,Personalization:/^(Base style and tone|Warm,|Enthusiastic,|Headers & Lists,|Emoji,|Open advanced settings$|Manage$)/,Plugins:/^(Permissions|Default templates$)/,Voice:/^(Model|Language)$/,Keyboard:/^Change key sequence$/, 'Data controls':/^(Improve the model for everyone|Information shared with apps$|Work network access|Manage Shared links$|Manage Archived chats$|Export Export data$|Marketing privacy$)/};
const normalized=(value:any)=>String(value??'').replace(/\s+/g,' ').trim();
export const settingsSignature=(c:any)=>[c.tag,c.role,c.name,c.id,c.testId,normalized(c.context)].join('|');
export function settingsControls(section:string,controls:any[]){const body=controls.filter(c=>c.role!=='tab'&&c.name!=='Close'&&c.role!=='searchbox'&&c.rect?.x>300);if(section!=='Keyboard')return body;return body.filter(c=>c.role==='switch'||c.name==='Change key sequence'||c.name==='Restore defaults');}
export async function settle(a:Actions):Promise<Snapshot>{let last='',stable=0,s=await a.snapshot();for(let i=0;i<14;i++){await Bun.sleep(250);s=await a.snapshot();const key=JSON.stringify(s.controls.map(c=>[c.name,c.role,c.value,c.checked]));stable=key===last?stable+1:0;last=key;if(i>=2&&stable>=2)break;}return s;}
export async function mapSettings(a:Actions,emit:(e:any)=>void=()=>{},selectedSections?:string[]){
 await a.settings();const initial=await settle(a),names=[...new Set(initial.controls.filter(c=>c.role==='tab').map(c=>c.name))],sections:any[]=[];
 if(!names.length)throw new Error('Settings navigation is unavailable.');
 for(const name of names.filter(name=>!selectedSections||selectedSections.includes(name))){await a.settings(name);const base=await settle(a),controls=settingsControls(name,base.controls);const section:any={name,controls:controls.map(c=>({...c,contract:settingsContract(c)})),nested:[],unexplored:[],at:new Date().toISOString()};
 section.unexplored=controls.filter(c=>c.tag==='button'&&!allowed[name]?.test(c.name)&&!/^Learn more/i.test(c.name)).map(c=>({name:c.name,reason:'Opening behavior unverified or action may mutate settings; requires fixture evidence.'}));
 const candidates=controls.filter(c=>allowed[name]?.test(c.name)&&!c.disabled);const visited=new Set<string>();
 for(const candidate of candidates){const key=settingsSignature(candidate);if(visited.has(key)){section.unexplored.push({name:candidate.name,scope:candidate.context,reason:'Repeated label requires a scoped field locator.'});continue;}visited.add(key);
  try{await a.settings(name);const fresh=await a.snapshot(),matches=fresh.controls.filter(c=>settingsSignature(c)===key);if(matches.length!==1){section.unexplored.push({name:candidate.name,scope:candidate.context,reason:'Ambiguous or unloaded control'});continue;}await a.press(fresh,matches[0]);const child=await settle(a);const before=new Set(base.controls.map(settingsSignature));const nested=name==='Keyboard'?child.controls.filter(c=>c.name==='Press the new key sequence'):child.controls.filter(c=>!before.has(settingsSignature(c))||['option','menuitemradio','menuitemcheckbox','radio','switch','combobox'].includes(c.role));section.nested.push({trigger:candidate.name,scope:candidate.context,controls:nested.map(c=>({...c,contract:settingsContract(c)})),text:child.text,confirmed:false});
   const cancel=child.controls.filter(c=>c.name==='Cancel');const close=child.controls.filter(c=>c.name==='Close');if(cancel.length===1)await a.press(child,cancel[0]);else if(close.length===1&&!child.controls.some(c=>c.role==='tab'))await a.press(child,close[0]);else{await a.b.call('key',{key:'Escape'});await Bun.sleep(150);}
  }catch(e:any){section.unexplored.push({name:candidate.name,scope:candidate.context,reason:e.message});await a.b.call('key',{key:'Escape'}).catch(()=>{});}
 }
 for(const control of section.controls)if(section.nested.some(n=>n.trigger===control.name&&(!n.scope||n.scope===control.context)))control.contract={...control.contract,evidence:'opened-without-selection'};
 for(const control of section.controls)if(control.contract.evidence==='requires-fixture'&&!section.unexplored.some(x=>x.name===control.name))section.unexplored.push({name:control.name,reason:'Write or unverified action contract; not executed during discovery.'});for(const nested of section.nested){nested.evidence='opened-without-selection';nested.sha256=createHash('sha256').update(JSON.stringify(nested.controls)).digest('hex');}
 sections.push(section);emit({type:'settings',section:name,count:controls.length,nested:section.nested.length});
 }
 return {schemaVersion:1,originalExport:SETTINGS_MAP_SCHEMA.originalExport,sections,navigationComplete:sections.length===names.length,complete:false,coverage:{sections:sections.length,nested:sections.reduce((n,s)=>n+s.nested.length,0),unexplored:sections.flatMap(s=>s.unexplored).length,reason:'Write controls were not executed. Account-conditional flows require additional fixture evidence.'},at:new Date().toISOString()};
}

export function exportAcknowledged(before:Snapshot,after:Snapshot,confirmation:string){const visible=after.controls.some(c=>c.name.trim()===confirmation.trim());const added=after.text.split('\n').filter(line=>!before.text.includes(line));return !visible&&added.some(line=>/data export requested|export (?:has been |was )?requested|export request (?:was |has been )?(?:received|submitted)|check your email/i.test(line));}

/** Public shape only. Captured values and dialog text belong in the private account directory. */
export const SETTINGS_MAP_SCHEMA={
 schemaVersion:1,
 evidenceLevels:['observed-control','opened-without-selection','requires-fixture'],
 section:{name:'string',at:'ISO timestamp',controls:'Control[]',nested:'NestedSurface[]',unexplored:'UnexploredContract[]'},
 control:{name:'string',role:'string|null',value:'unknown',checked:'unknown',selected:'unknown',contract:{kind:'inspect|open-options|write',evidence:'evidenceLevel',replay:'read-only|never'}},
 nestedSurface:{trigger:'exact observed control label',scope:'observed surrounding control context',controls:'Control[]',text:'private captured dialog text',confirmed:false},
 coverage:{sections:'number',nested:'number',unexplored:'number',complete:false},
 originalExport:{launcher:'Export Export data',confirmation:'Confirm export',dismiss:'Cancel',confirmed:false,successReceipt:'Confirmation absent plus a newly appeared explicit export-request acknowledgment; actual success wording still requires execution evidence.'},
} as const;
