import {test,expect} from 'bun:test';
import {settingsContract,settingsControls,settingsSignature,exportAcknowledged} from './settings-map.ts';
const snapshot=(text:string,controls:any[]=[])=>({text,controls}) as any;
test('settings writes are labeled as unexecuted contracts',()=>{for(const c of [{role:'switch',name:'Memory'},{name:'Delete account'},{name:'Reset ChatGPT Work'},{name:'Confirm export'}]){expect(settingsContract(c).replay).toBe('never');expect(settingsContract(c).evidence).toBe('requires-fixture');}});
test('option menu is inspectable but selecting its options is a write',()=>{expect(settingsContract({role:'combobox'}).replay).toBe('read-only');expect(settingsContract({role:'option'}).replay).toBe('never');});
test('keyboard shortcut launchers are read-only discovery but key capture remains a write',()=>{expect(settingsContract({tag:'button',name:'Change key sequence'})).toEqual({kind:'open-options',evidence:'observed-control',replay:'read-only'});expect(settingsContract({tag:'input',name:'Press the new key sequence'})).toEqual({kind:'write',evidence:'requires-fixture',replay:'never'});expect(settingsContract({tag:'button',role:'switch',name:'Toggle voice'}).replay).toBe('never');});
test('keyboard settings exclude controls behind the settings panel',()=>{const switches=Array.from({length:14},(_,i)=>({tag:'button',role:'switch',name:`Toggle ${i}`,rect:{x:600}}));const launchers=Array.from({length:14},(_,i)=>({tag:'button',name:'Change key sequence',context:`Toggle ${i}\nCommand-${i}`,rect:{x:600}}));const controls=[...switches,...launchers,{tag:'button',name:'Restore defaults',disabled:true,rect:{x:600}},{tag:'button',name:'Unrelated suggested prompt',rect:{x:900}},{tag:'div',role:'tabpanel',name:'Keyboard',rect:{x:500}},{tag:'button',name:'Close',rect:{x:700}},{tag:'button',role:'tab',name:'General',rect:{x:400}}];expect(settingsControls('Keyboard',controls)).toHaveLength(29);expect(settingsControls('Keyboard',controls).some(c=>c.name==='Unrelated suggested prompt'||c.role==='tabpanel')).toBe(false);});
test('repeated shortcut launchers have stable scoped signatures',()=>{const first={tag:'button',name:'Change key sequence',context:'Toggle voice\n⌘ Shift V'};const same={...first,context:'  Toggle voice  \n  ⌘ Shift V '};const second={...first,context:'Toggle dictation\n⌘ Shift D'};expect(settingsSignature(first)).toBe(settingsSignature(same));expect(settingsSignature(first)).not.toBe(settingsSignature(second));});
test('official export never treats pre-confirmation email explanation as success',()=>{const before=snapshot('The data will be sent to your registered email. Confirm export',[{name:'Confirm export'}]);expect(exportAcknowledged(before,before,'Confirm export')).toBe(false);expect(exportAcknowledged(before,snapshot('Settings'),'Confirm export')).toBe(false);expect(exportAcknowledged(before,snapshot('Settings\nData export requested'),'Confirm export')).toBe(true);expect(exportAcknowledged(before,snapshot('Data export requested',[{name:'Confirm export'}]),'Confirm export')).toBe(false);});
