import {expect,test} from 'bun:test';
import {ComposerNavigation,composerPositions,composerViewport,sentPrompts} from './tui-composer.ts';
import {graphemes,InputDecoder} from './tui-terminal.ts';
const draft=(text:string,cursor=graphemes(text).length,files:string[]=[])=>({text,cursor,files});
test('history contains only positively sent user prompts, preserving copies',()=>{const messages=[{role:'user',id:'confirmed',text:'one'},{role:'user',text:'two',delivery:'answered'},{role:'user',text:'three',delivery:'submitted'},{role:'user',text:'no',delivery:'unconfirmed'},{role:'user',text:'pending',delivery:'submitting'},{role:'draft',text:'draft'},{role:'assistant',id:'answer',text:'answer'}];expect(sentPrompts(messages).map(item=>item.text)).toEqual(['one','two','three']);});
test('top-line history recall restores exact composer attachment and cursor on Down',()=>{const nav=new ComposerNavigation(),messages=[{role:'user',id:'one',text:'first'},{role:'user',id:'two',text:'second'}],original=draft('my draft',2,['/tmp/image.png']);let value=nav.move(original,-1,80,messages);expect(value.text).toBe('second');value=nav.move(value,-1,80,messages);expect(value.text).toBe('first');value.text='edited recalled copy';value=nav.move(value,1,80,messages);expect(value.text).toBe('second');expect(nav.move(value,1,80,messages)).toEqual(original);expect(messages[0].text).toBe('first');});
test('vertical movement keeps preferred cell column through short and blank lines',()=>{const nav=new ComposerNavigation();let value=draft('abcdef\nx\n\nabcdef',5);value=nav.move(value,1,80,[]);expect(value.cursor).toBe(8);value=nav.move(value,1,80,[]);expect(value.cursor).toBe(9);value=nav.move(value,1,80,[]);expect(value.cursor).toBe(15);value=nav.move(value,-1,80,[]);expect(value.cursor).toBe(9);});
test('soft wraps and wide Unicode use intact graphemes and terminal columns',()=>{const text='a界👩‍💻e\u0301z';expect(graphemes(text)).toHaveLength(5);const positions=composerPositions(text,4);expect(positions[2]).toEqual({row:1,column:0});const nav=new ComposerNavigation();let value=nav.move(draft(text,1),1,4,[]);expect(value.cursor).toBe(2);expect(graphemes(value.text)[value.cursor]).toBe('👩‍💻');value=nav.move(value,-1,4,[]);expect(value.cursor).toBe(1);});
test('history navigation survives snapshot restore without losing original draft',()=>{const nav=new ComposerNavigation(),original=draft('draft',2,['file']);const recalled=nav.move(original,-1,80,[{role:'user',id:'one',text:'sent'}]);const restored=new ComposerNavigation();restored.restore(nav.snapshot());expect(restored.move(recalled,1,80,[])).toEqual(original);});
test('Shift+Enter and Ctrl+J insert lines, bracketed pasted Enter remains text',()=>{const decoder=new InputDecoder();expect(decoder.feed('\x1b[13;2u\x1b[27;2;13~\n\r')).toEqual([{key:'newline'},{key:'newline'},{key:'newline'},{key:'enter'}]);expect(decoder.feed('\x1b[200~a\r\nb\x1b[201~')).toEqual([{key:'text',text:'a\nb'}]);});

test('rendered caret never inserts a cell before wide characters or full-row newline',()=>{
 const wide=composerViewport('a界👩‍💻z',2,4,3);expect(wide.rows).toEqual(['a界','👩‍💻z']);expect(wide.cursor).toEqual({row:1,column:0});
 const beforeNewline=composerViewport('abcd\nx',4,4,3);expect(beforeNewline.rows).toEqual(['abcd','x']);expect(beforeNewline.cursor).toEqual({row:0,column:4});
 const afterNewline=composerViewport('abcd\nx',5,4,3);expect(afterNewline.cursor).toEqual({row:1,column:0});
 const full=composerViewport('abcd',4,4,2);expect(full.rows).toEqual(['abcd','']);expect(full.cursor).toEqual({row:1,column:0});
});
