import {clean,type Key} from './tui-terminal.ts';
type RPC=(op:string,args?:any)=>Promise<any>;
/** A sampled live browser view. Images travel in memory; no private screenshots persist. */
export class BrowserViewport {
 private active=false;private timer:ReturnType<typeof setTimeout>|undefined;private chain=Promise.resolve();private pixels={width:1200,height:800};private cells={width:120,height:40};
 constructor(private rpc:RPC,private draw:(image:string,status:string)=>void,private onError:(error:any)=>void){}
 async start(){if(!Bun.which('chafa'))throw new Error('Live browser view requires chafa. The browser control inspector is available with Ctrl+B.');this.active=true;process.stdout.write('\x1b[?1000h\x1b[?1006h');await this.resize();await this.refresh();}
 async resize(){this.cells={width:process.stdout.columns||80,height:Math.max(4,(process.stdout.rows||24)-3)};this.pixels={width:this.cells.width*10,height:this.cells.height*20};await this.rpc('ui.viewport',this.pixels);}
 stop(){this.active=false;clearTimeout(this.timer);process.stdout.write('\x1b[?1000l\x1b[?1006l');}
 private async refresh(){if(!this.active)return;try{const shot=await this.rpc('ui.screenshot');if(!shot?.base64)throw new Error('Browser screenshot unavailable. Use the control inspector.');const child=Bun.spawn(['chafa','--format=symbols','--colors=full','--size='+this.cells.width+'x'+this.cells.height,'--stretch','--animate=off','--probe=off','-'],{stdin:'pipe',stdout:'pipe',stderr:'pipe'});child.stdin.write(Buffer.from(shot.base64,'base64'));child.stdin.end();const output=await new Response(child.stdout).text();if(await child.exited!==0)throw new Error('Screenshot renderer failed');if(this.active)this.draw(output,'LIVE BROWSER · keyboard + mouse · Esc returns · sampled every 0.7s');}catch(e){if(this.active)this.onError(e);}finally{if(this.active)this.timer=setTimeout(()=>void this.refresh(),700);}}
 input(k:Key){this.chain=this.chain.then(async()=>{if(!this.active)return;if(k.key==='mouse'){const [button,x,y]=k.text!.split(';').map(Number);if(button===64||button===65)await this.rpc('ui.scroll',{dy:button===64?-420:420});else if(button===0)await this.rpc('ui.mouse',{x:(x-1)*10,y:Math.max(0,y-2)*20});return;}if(k.key==='text'){await this.rpc('ui.text',{text:clean(k.text)});return;}const names:Record<string,string>={enter:'Enter',newline:'Enter',tab:'Tab',backtab:'Tab',backspace:'Backspace',delete:'Delete',up:'ArrowUp',down:'ArrowDown',left:'ArrowLeft',right:'ArrowRight',home:'Home',end:'End'};if(k.key==='pageup'||k.key==='pagedown')await this.rpc('ui.scroll',{dy:k.key==='pageup'?-650:650});else if(names[k.key])await this.rpc('ui.key',{key:names[k.key],modifiers:k.key==='backtab'||k.key==='newline'?8:0});}).catch(this.onError);}
}
