import {expect,test} from 'bun:test';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {SharedQueue,queuePermissions,queueContextLabel} from './tui-shared-queue.ts';
import {MessageQueue} from './message-queue.ts';
const account={id:'shared-fixture',userId:'user',workspace:'space',label:'fixture',baseURL:'https://chatgpt.com',created:''};
function fixture(){const directory=mkdtempSync(join(tmpdir(),'tui-shared-queue-')),queue=new MessageQueue(account,{directory}),calls:string[]=[];let loseAdd=false;const rpc=async(op:string,args:any={})=>{calls.push(op);let item;if(op==='queue.add'){item=queue.add(args,args.clientId);if(loseAdd){loseAdd=false;throw new Error('Lost add response');}}else if(op==='queue.pause')queue.pause();else if(op==='queue.resume')queue.resume();else if(op!=='queue.list')throw new Error('Unexpected '+op);return {...queue.status(),...(item?{item}:{})};};return {queue,calls,shared:new SharedQueue(rpc,account),lose:()=>{loseAdd=true;},close:()=>rmSync(directory,{recursive:true,force:true})};}
test('CLI-origin queued items appear in shared TUI state with explicit context',async()=>{const f=fixture();try{const item=f.queue.add({text:'CLI message',conversation:'exact-chat'});await f.shared.refresh();expect(f.shared.state.items[0].id).toBe(item.id);expect(queueContextLabel(f.shared.state.items[0].draft)).toBe('conversation exact-chat');expect(f.calls).toEqual(['queue.list']);}finally{f.close();}});
test('lost migration response is retried by checkpointed client ID without duplicates or sends',async()=>{const f=fixture();try{const draft={id:'persisted-outbox-id',text:'preserved',files:[],context:{conversation:'exact-chat'}};const acknowledged:string[]=[];f.lose();await expect(f.shared.migrate([draft],id=>acknowledged.push(id))).rejects.toThrow('Lost add');expect(acknowledged).toEqual([]);const original=f.queue.status().items[0];await f.shared.migrate([draft],id=>acknowledged.push(id));expect(acknowledged).toEqual([draft.id]);expect(f.queue.status().items).toHaveLength(1);expect(f.queue.status().items[0].requestId).toBe(original.requestId);expect(f.queue.status().paused).toBe(true);expect(f.calls.some(op=>['queue.run','queue.resume','chat.send'].includes(op))).toBe(false);}finally{f.close();}});
test('unknown phase blocks shared run and offers reconciliation, never edit/retry/remove',async()=>{const f=fixture();try{f.queue.add({text:'uncertain',new:true});f.queue.resume();await f.queue.run(async()=>{throw new Error('lost response');});await expect(f.shared.run(()=>{})).rejects.toThrow('uncertain');expect(f.calls).toEqual(['queue.list']);expect(queuePermissions('unknown')).toEqual({edit:false,remove:false,reorder:false,retry:false,reconcile:true});}finally{f.close();}});
test('another account response leaves the local outbox unacknowledged',async()=>{const acknowledged:string[]=[];const shared=new SharedQueue(async()=>({account:{...account,userId:'wrong-user'},items:[],paused:true}),account);await expect(shared.migrate([{id:'id',text:'x',context:{new:true}}],id=>acknowledged.push(id))).rejects.toThrow('identity');expect(acknowledged).toEqual([]);});

test('pause is available during an active runner and does not dispatch chat.stop',async()=>{let finish!:(value:any)=>void;const calls:string[]=[];const state={account,items:[{id:'job',phase:'queued',draft:{new:true,text:'fixture'}}],paused:true,running:false};const shared=new SharedQueue(async(op:string,args:any,event:any)=>{calls.push(op);if(op==='queue.list')return structuredClone(state);if(op==='queue.resume'){state.paused=false;return structuredClone(state);}if(op==='queue.run'){state.running=true;event({type:'queue.submitting',id:'job'});return new Promise(resolve=>{finish=resolve;});}if(op==='queue.pause'){state.paused=true;return structuredClone(state);}throw new Error(op);},{...account});const running=shared.run(()=>{});while(!finish)await Bun.sleep(1);expect(shared.pending).toBe(true);await shared.mutate('pause');expect(shared.state.paused).toBe(true);expect(calls).toContain('queue.pause');expect(calls).not.toContain('chat.stop');finish({...state,running:false});await running;});
test('first bound receipt fixes website identity for subsequent responses',async()=>{let userId='first-user';const shared=new SharedQueue(async()=>({account:{id:'unbound',userId},items:[],paused:true}),{id:'unbound'});await shared.refresh();userId='other-user';await expect(shared.refresh()).rejects.toThrow('identity');expect(shared.state.account.userId).toBe('first-user');});

test('mixed-target streamed text, thinking and media remain in separate queue projections',async()=>{const {sharedQueueTranscript}=await import('./tui-shared-queue.ts');let release!:(value:any)=>void;const base={account,paused:true,running:false,items:[{id:'a',requestId:'ra',created:'2026-09-15T00:00:00Z',phase:'queued',draft:{conversation:'other-chat',text:'first'}},{id:'b',requestId:'rb',created:'2026-09-15T00:00:00Z',phase:'queued',draft:{new:true,text:'second'}}]};const shared=new SharedQueue(async(op:string,args:any,event:any)=>{if(op==='queue.list'||op==='queue.resume')return structuredClone(base);if(op==='queue.run'){event({type:'queue.submitting',id:'a'});event({type:'queue.event',id:'a',event:{type:'text',text:'partial'}});event({type:'queue.event',id:'a',event:{type:'replace',text:'complete first'}});event({type:'queue.event',id:'a',event:{type:'thinking',items:[{id:'thought',title:'Observed thought',text:'full detail'}]}});event({type:'queue.event',id:'a',event:{type:'media',items:[{reference:'file-123',kind:'image'}]}});event({type:'queue.event',id:'b',event:{type:'text',text:'second target'}});return new Promise(resolve=>{release=resolve;});}throw new Error(op);},{...account});const running=shared.run(()=>{});while(!release)await Bun.sleep(1);const projected=sharedQueueTranscript(shared.state,shared.details);expect(projected[0].text).toContain('other-chat');expect(projected.find((item:any)=>item.id==='a-response')).toMatchObject({text:'complete first',thinking:[{id:'thought',text:'full detail'}],media:[{reference:'file-123'}]});expect(projected.find((item:any)=>item.id==='b-target').text).toContain('new conversation');expect(projected.find((item:any)=>item.id==='b-response').text).toBe('second target');release({...base,running:false});await running;});

test('richer persisted/final queue details supersede an old detached view',async()=>{const {sharedQueueTranscript}=await import('./tui-shared-queue.ts');const state={items:[{id:'a',phase:'complete',draft:{conversation:'chat',text:'prompt'},created:'2026-09-15T00:00:00Z',updated:'2026-09-15T00:00:05Z',thinking:[{id:'thought',title:'Thought',text:'persisted full'}],media:[{id:'image1',url:'final-image1'},{id:'image2',url:'image2'}],result:{text:'final answer',thinking:[{id:'thought',title:'Thought',text:'final full'}],media:[{id:'image3',url:'image3'}]}}]};const details={a:{text:'partial',timestamp:'2026-09-15T00:00:00Z',thinking:[],media:[{id:'image1',url:'old-image1'}]}};const reply=sharedQueueTranscript(state,details).find((message:any)=>message.role==='assistant');expect(reply.text).toBe('final answer');expect(reply.thinking[0].text).toBe('final full');expect(reply.media.map((item:any)=>item.id)).toEqual(['image1','image2','image3']);expect(reply.media[0].url).toBe('final-image1');});

test('dependent direct-send uncertainty guard runs against freshest queue state before resume',async()=>{const f=fixture();try{f.queue.add({text:'follow-up',conversation:'uncertain-chat'});await expect(f.shared.run(()=>{},state=>{if(state.items.some((item:any)=>item.draft.conversation==='uncertain-chat'))throw new Error('Reconcile parent send');})).rejects.toThrow('Reconcile parent');expect(f.calls).toEqual(['queue.list']);expect(f.queue.status().paused).toBe(true);}finally{f.close();}});
