import {afterAll,expect,test} from 'bun:test';
import {mkdtempSync,readFileSync,rmSync,statSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
const home=mkdtempSync(join(tmpdir(),'observed-history-'));process.env.CHATGPT_HOME=home;afterAll(()=>rmSync(home,{recursive:true,force:true}));
const {seedObservedHistory,readObservedHistory}=await import('../../src/chatgpt/observed-history.ts');
const a={id:'fixture',userId:'fixture-user',workspace:'workspace',label:'fixture',baseURL:'https://chatgpt.com',created:''};
const old={url:'https://chatgpt.com/c/exact-conversation',text:'raw source retained',messages:[{id:'1',role:'assistant',text:'old1'},{id:'2',role:'user',text:'old2'},{id:'3',role:'user',text:'old3'},{id:'4',role:'assistant',text:'overlap answer'},{id:'5',role:'user',text:'overlap prompt'}]};
const current={url:old.url,messages:[...old.messages.slice(3),{id:'6',role:'user',text:'new prompt'}]};
const source={sourcePath:'/private/tmp/verified-old-source.json',observedAt:'2026-09-15T13:00:00.000Z'};
test('private raw seed restores five-old/three-mounted prefix through ordered IDs',()=>{const result=seedObservedHistory(a,old,source);expect(statSync(result.path).mode&0o777).toBe(0o600);expect(JSON.parse(readFileSync(result.path,'utf8')).rawSnapshot).toEqual(old);const merged=readObservedHistory(a,current);expect(merged.messages.map((message:any)=>message.id)).toEqual(['1','2','3','4','5','6']);expect(merged.coverage).toMatchObject({complete:false,retainedPrefix:3,seedApplied:true});});
test('recovery never overwrites raw source and remains account/user/workspace bound',()=>{expect(seedObservedHistory(a,old,source).reused).toBe(true);expect(()=>seedObservedHistory(a,{...old,text:'changed'},source)).toThrow('existing history seed');expect(()=>readObservedHistory({...a,userId:'another'},current)).toThrow('account');expect(()=>readObservedHistory({...a,workspace:'another'},current)).toThrow('account');});
test('unanchored or another conversation never receives a guessed historical prefix',()=>{expect(readObservedHistory(a,{url:old.url,messages:[{id:'unrelated',role:'user',text:'other'}]}).coverage).toMatchObject({complete:false,seedApplied:false});const other=readObservedHistory(a,{url:'https://chatgpt.com/c/another',messages:[]});expect(other.messages).toEqual([]);expect(other.coverage.complete).toBe(false);});
test('conflicting shared message role or ordering rejects the merge',()=>{expect(()=>readObservedHistory(a,{url:old.url,messages:[old.messages[4],old.messages[3]]})).toThrow('order or role');expect(()=>readObservedHistory(a,{url:old.url,messages:[{...old.messages[3],role:'user'}]})).toThrow('order or role');});

test('service reconciliation exposes recovered history without navigation or send',async()=>{const {ChatGPTService}=await import('../../src/chatgpt/service.ts');const service=Object.create(ChatGPTService.prototype);service.account=a;service.start=async()=>{};service.actions={snapshot:async()=>({...current,controls:[],thinking:[],media:[]})};const result=await service.execute('chat.reconcile',{conversation:'exact-conversation'});expect(result.messages.map((message:any)=>message.id)).toEqual(['1','2','3','4','5','6']);expect(result.historyCoverage).toMatchObject({complete:false,retainedPrefix:3});expect(result.verified).toBe(true);await expect(service.execute('chat.reconcile',{conversation:'wrong'})).rejects.toThrow('another conversation');});
